[1단계 - 상품 목록] 쿠키(김진호) 미션 제출합니다.
woowacourse/react-shopping-products pull request #10
Opened 2024-05-30 08:05 UTC by jinhokim98

안녕하세요 지그! 6기 FE 리뷰이 쿠키입니다!
상품 목록 미션 제출합니다!

## 🎡배포 주소
아래 링크를 접속하시면 상품 목록 서비스를 이용하실 수 있습니다.
backend가 http로 배포되어있어 브라우저 사이트 설정의 안전하지 않은 컨텐츠 허용을 눌러주셔야 확인하실 수 있습니다.
[배포링크](https://jinhokim98.github.io/react-shopping-products/)

## 🗃️ 컴포넌트 구조
![image](https://github.com/woowacourse/react-shopping-products/assets/81083461/b4f14a28-6679-46d6-a384-02bbc4a96c70)

## 🚀 흐름도
![image](https://github.com/woowacourse/react-shopping-products/assets/81083461/0b5a6d3b-d40d-48e6-97f6-40bfee1ac2a4)
![image](https://github.com/woowacourse/react-shopping-products/assets/81083461/74f46c12-888a-4260-a558-0e28a4e83452)
![image](https://github.com/woowacourse/react-shopping-products/assets/81083461/02402cf8-432a-4ef9-b10c-4fa4d024f664)

## 🤔 고민한 점과 질문
1. msw get 외의 test를 진행할 때의 고민
get 메서드를 테스트할 때는 파라미터에 따라서 조건을 나눠서 그에 맞는 응답을 내려주는 핸들러를 작성하기 쉬웠습니다. 그러나 delete나 post와 같이 서버의 상태를 변경 시키는 함수를 테스트할 때는 서버의 값이 변해야 하지만 이를 모킹 하기가 쉽지 않았습니다. 이런 상황에서는 어떻게 테스트를 진행하면 좋을지 고민입니다.

2. 담기 빼기 요청을 할 때의 헤더의 수량 동기화 고민
피그마 구조를 보면 공통적으로 사용하는 헤더에 장바구니 수량이 있고, 페이지 안에 장바구니 담기 빼기 버튼이 있습니다. 담기 빼기를 조작할 때 헤더에 장바구니 수량을 동기화 시키기 위해서 앱 단에서 상태를 들고 헤더와 아래 컴포넌트에 props로 계속 넣어주어야 하더라구요... 관심사에 맞는

2024-05-30 12:35 UTC, zigsong requested changes
안녕하세요 쿠키~ 리뷰를 맡은 지그입니다 :D 

API 호출이 까다로웠던 이번 미션도 힘차게 잘 시작해주셨네요! 

전반적으로 구조 개선을 할 수 있는 부분이 있어 코멘트 남겼어요. 

다음은 본문에 대한 답변입니다 

---

1. msw get 외의 test를 진행할 때의 고민
       
    → 사실 MSW가 실제 서버처럼 DB를 유지하는 것이 아니기 때문에, DELETE와 POST 액션의 응답까지 실제처럼 완벽하게 구현하기는 어렵습니다. 현재 미션 swagger에도 DELETE, POST 시 별다른 응답값을 반환하는 것이 아니기 때문에, 204, 201 등의 올바른 응답 상태와 함께 요청이 성공했는지 등만 테스트하셔도 될 것 같습니다. 
    
2. 담기 빼기 요청을 할 때의 헤더의 수량 동기화 고민
        
    → 다른 여러 코멘트에도 남겼지만, `useCartAction` hook을 해체하여 App에서는 상품 목록을 불러오는 API만 호출하고, 추가/삭제 등 다른 API들은 쿠키가 말씀하신 대로 각 컴포넌트의 관심사에 맞게 호출해야 합니다. 지금 모든 문제가 방대한 `useCartAction` 으로부터 시작하고 있으니, 해당 hook을 제거하시는 것부터 하시면 됩니다. 
    
- 추가로 장바구니 데이터 response 형식이 pagination입니다. ...
    
    → 무슨 말인지 이해하지 못했습니다. 문장을 순서대로, 구체적인 예시를 들어서 설명해주시겠어요?

2024-05-30 12:35 UTC, zigsong commented on src/pages/ProductListPage/index.tsx
> +    fetch,
`useFetch<typeof fetchProduct>(fetchProduct);`에서 반환하는 `fetch`는 결국 `fetchProduct`를 가리키는데, 

그걸`fetch`를 다시 `useStackProducts`에 넣어서, 결과적으로 `useStackProducts`에서 `fetchProduct`를 호출하고 있네요? 

loading과 error를 위해 `useFetch`를 사용하신 의도는 알겠으나, 결과적으로 같은 코드를 두 번 찾아서 들어가야 해 코드의 복잡도가 커집니다.

가장 간단하게 리팩토링할 수 있는 방식은 `useFetch`를 컴포넌트가 아닌 `useStackProducts` 안에서 호출하는 것이고,

더 나은 방법은 `useStackProducts`가 더 작은 역할만 할 수 있도록 인자의 수를 줄이고 `fetchProduct`에만 집중하도록 하는 것입니다.

이미 리팩토링할 것이 많아 더 쉬운 방법을 추천드려요. 

그리고 전반적으로 앱의 추상화에 힘을 많이 쓰신 것 같은데, 크지 않은 요구사항에 '어떻게 추상화하지?' 부터 너무 심도있게 고민하며 시작하신 느낌이 납니다. 기본적으로 요구사항을 먼저 충족하는 직관적인 코드를 구현한 후에, 추상화할 것들을 찾아 개선해나가시는 게 좋습니다.

2024-05-30 12:35 UTC, zigsong commented on src/pages/ProductListPage/index.tsx
> +    fetch,
`useFilteredProducts`도 마찬가지입니다. 그리고 혹시 가능하다면, (다른 리팩토링을 모두 한 후에 마지막으로.) `useStackProducts`와 `useFilteredProducts`를 하나로 합치는 것도 고려해주세요!

2024-05-30 12:35 UTC, zigsong commented on src/components/Header/index.tsx
> +    <>
불필요한 Fragment가 들어가 있어요~

2024-05-30 12:35 UTC, zigsong commented on src/components/Header/CartBadgeButton/index.tsx
> +const BADGE_MAX_QUANTITY = 50;
50개가 MAX라는 요구사항이 있었나요? 👀 (제가 놓쳤을 수도 있어 여쭤봅니다)

2024-05-30 12:35 UTC, zigsong commented on src/components/IntersectionObserverArea/index.tsx
> +  const observer = new IntersectionObserver(callback, { threshold: 1 });
`IntersectionObserver`를 정석대로 잘 구현하셨네요 👍

2024-05-30 12:35 UTC, zigsong commented on src/hooks/tests/useStackProducts.test.ts
> +      return { getStackedProducts };
다른 코멘트에도 남겼듯, `useFetch`와 `useStackProducts`가 불필요하게 섞여있어 테스트를 작성할 때도 `renderHook`에서 에러 발생 시 `useFetch`와 `useStackProducts` 둘 중 어느 hook에서 문제가 발생한 것인지 추적이 어려워지게 됩니다.

2024-05-30 12:35 UTC, zigsong commented on src/mocks/handlers/products.ts
> +};
sorting은 프론트가 아닌 서버에서 해서 주나보군요?

2024-05-30 12:35 UTC, zigsong commented on src/mocks/handlers/products.ts
> +    const sortedProducts = sortProducts(sort, filteredProducts);
요구사항이 이렇게까지 들어가는지는 모르겠지만, 스크롤을 통해 목록을 더 받아온 후 필터에서 sorting을 선택하면 정상적으로 아이템 sorting이 되지 않는 문제가 있습니다.

사실 무한 스크롤을 하며 sorting을 유지하는 것은 매우 까다로워 보이는데요, 혹시 이에 대한 가이드가 있었을까요?

2024-06-02 02:20 UTC, jinhokim98 commented on src/components/Fallbacks/CartAction/index.tsx
> +}
앗 작은 화면에서는 잘렸네요! 수정해보겠습니다😊

2024-06-02 02:22 UTC, jinhokim98 commented on src/hooks/useCartAction.ts
> +  const deleteFetchResult = useFetch<typeof fetchDeleteCartItems>(fetchDeleteCartItems);
저도 그런 것 같아요! 적절하게 분리해보겠습니다

2024-06-02 02:23 UTC, jinhokim98 commented on src/apis/cartItems.ts
> +}
앗 그렇군요! 저는 안에서 계산한 후에 필요한 값만 바깥으로 제공해주자는 의미에서 이렇게 작성했었는데 개선해보겠습니다

2024-06-02 02:27 UTC, jinhokim98 commented on src/components/Fallbacks/CartAction/index.tsx
> +function CartAction() {
cartAction에서 발생하는 에러일 때 보여주기 위해서 CartAction이라고 지었습니다.
Fallback 디렉토리 안에 CartActionFallback이라는 중복적인 이름을 피하기 위해서였어요.
뒤에 Error라고 이름을 붙여도 좋았을 것 같네요

2024-06-02 02:27 UTC, jinhokim98 commented on .eslintrc.cjs
> +        alphabetize: {
앗... 페어 프로그래밍 하다가 toast popup의 경우 페어의 코드를 사용하느라...
이 부분을 놓쳐버렸네요;;;;

2024-06-02 02:33 UTC, jinhokim98 commented on src/components/Header/CartBadgeButton/index.tsx
> +const BADGE_MAX_QUANTITY = 50;
50개가 요구사항은 아니지만 장바구니에 너무 많이 담았을 때 숫자가 깨지는 것이 좋은 경험을 제공할 것 같지 않아서 50개 이상일 때는 +로 보이도록 설정했습니다.

2024-06-02 02:34 UTC, jinhokim98 commented on src/mocks/handlers/products.ts
> +};
네 맞아요! 서버에서 정렬, 필터링을 해서 줍니다

2024-06-02 02:36 UTC, jinhokim98 commented on src/mocks/handlers/products.ts
> +    const sortedProducts = sortProducts(sort, filteredProducts);
흐음🤔 그렇군요. 리팩토링 하면서 버그도 고쳐볼게요!

2024-06-02 10:47 UTC, jinhokim98 commented on src/App.tsx
> +  }, [headerRef]);
그렇네요 header의 position을 사용하는 것이 toast이니깐 toastPosition이 더 적절한 이름인 것 같아요.

그리고 수정하면서 headerRef와, toastPosition을 사용하지 않고 createPortal을 사용해서 고정된 위치에 띄우는 방식으로 변경했습니다!

2024-06-02 10:47 UTC, jinhokim98 commented on src/components/Modal/ToastModal/index.tsx
> +const ToastModal = ({ children, position, isOpen, closeModal, ...rest }: ToastModalProps) => {
아니오 크게 필요 없을 것 같아서 리팩토링할 때 rest는 지워주었습니다!

2024-06-02 10:48 UTC, jinhokim98 commented on src/components/Modal/ModalPortal/index.tsx
> +  return createPortal(<div className={style.modalPortal}>{children}</div>, modalRoot || document.body, 'modal-portal');
createPortal을 살리고 위치를 계산하는 방식을 지웠습니다.
디자인 상 header의 height 값은 고정되어있고, 이를 굳이 계산할 필요가 없는 것 같아서 지웠습니다!

2024-06-02 10:53 UTC, jinhokim98 commented on src/pages/ProductListPage/ProductCard/index.tsx
> +      </div>
useCartAction에서 서버의 변경을 일으키는 함수를 useAddCartItem, useDeleteCartItem 두 개의 훅으로 분리해서 CartActionButton 안에서 호출해서 사용하는 방식으로 변화시켰고, context를 사용하지 않는 방법으로 변경해봤습니다!
[098a9b7](https://github.com/woowacourse/react-shopping-products/pull/10/commits/098a9b7f9cc436a897bd0fd4a14b0a9c9ff8eb52)

2024-06-02 10:56 UTC, jinhokim98 commented on src/contexts/CartItemsContext.ts
> +  }) => Promise<void> | undefined;
훅을 분리하면서 CartActionButton 내에서 서버 변경 훅을 호출해서 사용하니 handleCartAction을 context로 내려줄 필요가 없게 되었습니다. 좋은 리뷰 감사합니다!

2024-06-02 11:02 UTC, jinhokim98 commented on src/pages/ProductListPage/index.tsx
> +    fetch,
우선 useFetch를 지우고 각 api 함수 호출부에 try catch를 사용해서 직관적으로 보일 수 있도록 변경해봤습니다.
[74db438](https://github.com/woowacourse/react-shopping-products/pull/10/commits/74db438eb865c46dec147174f22f301eb5104bf7)

그리고 stack과 filter를 하나로 합쳐서 useLoadProducts라는 훅을 만들어보았고, 
상품목록, 다음 페이지를 부르는 함수, 필터링이 바뀌면서 상품을 리셋을 관리하도록 리팩터링 해봤습니다.

확실히 두 개를 하나로 합치니 받는 인자도 필터링 밖에 없어지고, 이 훅을 사용하는 외부에서도 보기 깔끔해진 것 같아 더 좋은 결과가 나온 것 같아요!

2024-06-02 11:04 UTC, jinhokim98 commented on src/hooks/useStackProducts.ts
> +const useStackProducts = ({ fetch, products, filtering, isLast, productLength }: UseStackProductsProps) => {
그렇네요.. 뭔가 상품이 쌓인다는 생각에 stack으로 이름을 지었던 것 같은데 다른 네이밍이 더 좋았을 것 같아요! 리팩터링 결과 없어지긴했지만!

2024-06-02 11:04 UTC, jinhokim98 commented on src/hooks/useCartAction.ts
> +  };
개선해봤습니다!
[74db438](https://github.com/woowacourse/react-shopping-products/pull/10/commits/74db438eb865c46dec147174f22f301eb5104bf7)

2024-06-02 11:04 UTC, jinhokim98 commented on src/components/Header/index.tsx
> +    <>
앗. 그러네요!
[2b59974](https://github.com/woowacourse/react-shopping-products/pull/10/commits/2b599749e5d8d28b3949b727bbd81d5983ad64ba)

2024-06-02 11:06 UTC, jinhokim98 commented on src/hooks/tests/useStackProducts.test.ts
> +      return { getStackedProducts };
그러네요! 개선해본 결과 훅 한 개만 불러도 테스트가 정상적으로 돌아가게 됐습니다.
[69c31e6](https://github.com/woowacourse/react-shopping-products/pull/10/commits/69c31e634d0621098b8f2a4e0eeddff1e9d62ea5)

2024-06-02 11:28 UTC, jinhokim98 commented
안녕하세요 지그! 주말 잘 지내셨나요?
글쓰기 미션과 다른 여러가지가 일이 겹쳐서 리뷰 반영이 조금 늦었습니다🥲🥲

페이지네이션 문제를 조금 더 자세히 설명해드리면

제가 장바구니를 21개를 담았다고 가정해보겠습니다.
처음 페이지에 접속했을 때, 장바구니 목록을 get하는 api를 호출하게 되면 서버로부터 장바구니에 담긴 리스트를 받게 됩니다. 이 때 서버의 페이지네이션 사이즈의 defalut가 20개로 셋팅 되어있습니다.  그러면 서버로부터 페이지네이션 default 사이즈인 20개를 받게 되어 실제로는 21개를 담았지만 온전하게 데이터를 받을 수가 없습니다..
그래서 요청을 해서 pagination의 정보에서 아래 사진에 있는 totalElements 값을 들고 와서 아래 swagger에 있는 size 파라미터에 totalElements 값을 넣고 다시 호출해야 내가 장바구니에 담은 item들을 온전하게 받을 수 있다는 뜻이었습니다.

![image](https://github.com/woowacourse/react-shopping-products/assets/81083461/6be6408e-04b3-414e-8133-3a1750646598)
![image](https://github.com/woowacourse/react-shopping-products/assets/81083461/1fd7df57-a44a-4ca2-81ba-20067bfb76f9)

리뷰해주신 useCartAction 훅의 분리와 product를 불러오는 훅을 주로 리팩터링 해봤습니다.
useCartAction의 역할을 분리하고 각각 관심사에 맞는 컴포넌트에서 훅을 호출해서 사용하니 가독성이 많이 좋아진 느낌이 듭니다!
stack과 filter로 나뉘어져 있던 두 개의 훅을 하나로 합쳐서 관리하다 보니 인자도 적어지고, 밖에서 사용하는 쪽도 간소화해져서 더 보기 좋은 코드가 나온 것 같습니다!
좋은 리뷰 감사드립니다.

반영한 내용에는 커밋 번호를 달아두었으며, 제 의견을 추가로 리코멘트에 적어두었습니다.
그러면 남은 주말 잘 보내시고 힘찬 한 주 보내시길 바랍니다!

2024-06-03 11:06 UTC, zigsong commented on src/components/Fallbacks/CartAction/index.tsx
> +}
사소하지만 피그마에 맞추려면 두 줄이 아니라 한 줄로 나와야 할 것 같아요 😅 

<img width="448" alt="image" src="https://github.com/woowacourse/react-shopping-products/assets/44080404/3b25ef6b-d76b-44df-9991-6fbebc77969f">

![image](https://github.com/woowacourse/react-shopping-products/assets/44080404/eba70785-b903-4712-b851-a9c0606d3e3d)

2024-06-03 11:07 UTC, zigsong commented on src/App.tsx
> +  }, [headerRef]);
하나만 말씀드렸는데 두 개 이상을 잘 리팩토링해주셨네요 😀

2024-06-03 11:09 UTC, zigsong commented on src/hooks/useDeleteCartItem.ts
> +const useDeleteCartItem = (refetch: () => Promise<void>) => {
코드 복붙하다가 여기만 이름 수정을 깜박한 것 같아요 😅

2024-06-03 11:09 UTC, zigsong commented on src/hooks/useDeleteCartItem.ts
> +  const deleteCarItem = async (cartItem: CartItem | undefined) => {
여기도 갑자기 `CarItem`이 되었어요 🙃

2024-06-03 11:09 UTC, zigsong commented on src/hooks/useCartAction.ts
> +  const deleteFetchResult = useFetch<typeof fetchDeleteCartItems>(fetchDeleteCartItems);
훨씬 깔끔해졌네요 😄

2024-06-03 11:11 UTC, zigsong commented on src/apis/cartItems.ts
> +}
필요한 값만 바깥으로 제공해주는 것도 좋지만, 그러려면 이 API 파일과 컴포넌트 사이에 하나의 레이어가 더 있는 것이 좋습니다 (ex. 상태 store 등) 

다른 개발자가 보기에 이 파일의 함수는 API 반환값을 전달해주는 역할만 할 거라고 생각하고 있는데, 알고보니 계산된 값을 내려주고 있다는 건 예측이 어려운, 아쉬운 코드가 되겠죠

2024-06-03 11:12 UTC, zigsong commented on src/hooks/useStackProducts.ts
> +const useStackProducts = ({ fetch, products, filtering, isLast, productLength }: UseStackProductsProps) => {
ㅋㅋㅋㅋ 없어졌지만! 먼가 웃기네용

2024-06-03 11:14 UTC, zigsong commented on src/pages/ProductListPage/index.tsx
> +    fetch,
제가 설명을 구구절절 어렵게 드린 것 같은데도 착 리팩토링을 잘 해주셨네요 👍

2024-06-03 11:16 UTC, zigsong commented on src/mocks/handlers/products.ts
> +    const sortedProducts = sortProducts(sort, filteredProducts);
코치님들께 여쭤봤더니, 

> 카테고리 및 정렬 적용 시 해당 값을 적용하여 첫 페이지부터 다시 불러오는 방식으로 처리하는 것도 괜찮다 

라고 하시네요 :D 

사실 무한스크롤을 유지하며 sorting을 완벽하게 구현하기 위해서는 서버의 도움이 필요한데, 쿠키처럼 한번 비워주고 sorting한 결과를 보여주는 것도 현재 상황에선 좋은 선택인 것 같습니다 😉

2024-06-03 11:23 UTC, zigsong commented
@jinhokim98 `totalElements`와 refetch 관련 설명 주신 내용을 읽어봤습니다. 다른 크루의 PR을 통해서 `totalElements`가 '사용자가 담아둔 장바구니 목록 개수'라는 것을 알았습니다 😅 제가 API 응답을 잘 몰라서 처음에 쿠키의 설명도 이해하지 못했던 것 같아요. 

사실 이번 미션은 프론트에서의 이런 케이스를 대응하지 못하고 프론트-서버 사이의 커뮤니케이션이 없었기 때문에, 즉 서버 API에 프론트의 의견이 반영되지 않아서 refetch를 해와야 하는 경우가 발생한 것 같아요. 다른 크루들의 케이스에서도 확인했는데, 처음 말씀 주신 대로 요청을 2번 보내는 수밖에 없을 것 같습니다. 

그래도 이 부분도 hook 분리를 통해 코드의 흐름을 개선해주셔서 어느 정도 해결된 것 같네요! 👍

2024-06-03 11:30 UTC, zigsong approved these changes
안녕하세요 쿠키~ 

앱의 여러 주요 로직들을 바꾸는 작업이 쉽지는 않았을 텐데, 의도대로 멋지게 잘 구현해주셨네요! 

여러 API를 호출하고 mocking하는 데 있어 기초를 탄탄히 하고 가실 수 있게 된 것 같아요 :) 

추가로 소소한 코멘트 남겼으니, 2단계에서 마저 힘내보아요! 💪

2024-06-03 11:30 UTC, zigsong commented on src/hooks/tests/useAddCartItem.test.ts
> +      expect(mutate).not.toThrow();
단순히 에러를 던지지 않는 것이 중요한 것이 아니기 때문에

기대 결과를 좀 더 구체적으로 바꿔봐도 좋을 것 같아요 :)

2024-06-03 11:30 UTC, zigsong commented on src/hooks/useLoadCartItems.ts
> +      const errorMessage = (error as Error).message;
`Error` 타입의 에러가 아니라면 `.message`를 읽어오는 과정에서 다시 한번 에러가 날 수 있기 때문에,

`if (error instanceof Error) ~` 등의 구문으로 가드해주는 것이 좋아요!

2024-06-03 11:30 UTC, zigsong commented on src/pages/ProductListPage/ProductList/index.tsx
> +        {loading && <div>로딩중....</div>}
`{ loading ? <div>로딩중...</div> : products.map(...)}` 으로 작성하는 것이 더 정확합니다.

지금은 `products.map(...)`을 렌더링하는 코드는 `loading` 상태와 상관없이 실행될 테니까요!

2024-06-03 11:30 UTC, merged