[1단계 - 상품 목록] 제이드(전세영) 미션 제출합니다.
woowacourse/react-shopping-products pull request #21
Opened 2024-05-30 08:24 UTC by skiende74

안녕하세요 케빈 ! 다시 뵙게되었네요 :)
잘부탁드립니다.😊
이번에 TDD로 작성해보았습니다.

## 배포 링크 : [클릭](https://react-shopping-products-five.vercel.app/)
![image](https://github.com/woowacourse/react-shopping-products/assets/86130706/74f80f7e-9303-4ed3-8483-4556b80297d8)
- 처음 페이지에 들어가시면, (사이트설정 - 안전하지 않은 콘텐츠 [허용] ) 눌러주셔야 합니다 :)

코드 봐 주셔서 감사합니다 ! :)

2024-05-30 08:48 UTC, skiende74 commented on src/hooks/useFetchProducts.test.ts
> +  // });
이 테스트 코드를 실행해보면,
20개가 불러와진 다음에,  24개가 아니라, 3000개 가량이 불러와 지는데요.
4개씩불러오는 로직이 수백번 실행되는 현상입니다.

데브서버나, 프로덕션에서 fetchNextPage()를  실행해봐도 무한fetching이 일어나지않고,
코드를보아도 무한정 fetch할만한 이유가 없는 것 같아서 의아합니다.

43번줄을
await act(async()=> await result.current.fetchNextPage()); 로 바꿔주어도 동일했습니다.
실제 fetch하는 코드는 43번줄인데 waitFor를 해준 게아니고 단순 act를 하였기때문에 43번콜백도 한번만실행될텐데
왜 무한렌더링이 일어나는지 짚이는 곳이 있으실까요?

2024-06-01 04:13 UTC, JeongBin0227 requested changes
안녕하세요 제이드~

전체적인 코드를 확인해봤는데, 정말 잘 짜신거 같아요 저도 이렇게 비슷하게 짰을거 같아요. 사실 처음에 어떤걸 리뷰할지 몰라서 계속보다가 세세한것도 드렸는데 가볍게 읽어만 주시면 될거같아요

고생하셨습니다~

2024-06-01 04:13 UTC, JeongBin0227 commented on src/components/AddCartButton/AddCartButton.tsx
> +  const [isClicked, setIsClicked] = useState(false);
가독성과 의존성을 위해 useEffect 보다 위에 있으면 어떨까요?

2024-06-01 04:13 UTC, JeongBin0227 commented on src/components/AddCartButton/AddCartButton.tsx
> +  );
alt 태그도 있으면 좋을거 같아요

2024-06-01 04:13 UTC, JeongBin0227 commented on src/components/ErrorMessage/ErrorMessage.tsx
> +export default ErrorMessage;
지금을 디폴트로 두고,
메시지를 커스텀하게 받을 수 있도록 하면 어떨까요?

2024-06-01 04:13 UTC, JeongBin0227 commented on src/components/Dropdown/Dropdown.tsx
> +export default Dropdown;
직접 핸들러를 직접할당보다, 함수로 두는게 재사용성이나 가독성에 좋을거같아요

```
const handleFilterChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
  setFilter(event.target.value);
};

const handleSortingChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
  setSortings([{ name: 'price', order: event.target.value } as SortingParam]);
};

```

2024-06-01 04:13 UTC, JeongBin0227 commented on src/utils/productSorter.ts
> +  const products = [...productCopy.content];
const products = productCopy.content.slice();
불변성을 유지해보면 어떨까요?

2024-06-01 04:13 UTC, JeongBin0227 commented on src/utils/productSorter.ts
> +    }
return order === 'desc' ? -comparison : comparison;
참고차,요런것도 있습니다~

2024-06-04 07:21 UTC, skiende74 commented on src/utils/productSorter.ts
> +  const products = [...productCopy.content];
[...productCopy.content]도
productCopy.content라는 배열을 구조분해하여 새로생성하기때문에 
둘 다 불변성을 유지하는 것으로 이해하고있는데, 혹시 제가 잘못이해하고있을까요?

2024-06-04 07:26 UTC, skiende74 commented on src/utils/productSorter.ts
> +    }
감사합니다 :)
9번줄과 11번줄에 return order==='desc'? -기존조건문 : 기존조건문
하는 방법도 있다는 말씀으로 이해했습니다

2024-06-05 08:19 UTC, skiende74 commented
안녕하세요 케빈 !

이번에 리뷰해주신 것을 반영해보았습니다.

ErrorMessage는 메시지를 prop으로 받기.
단순 변수/함수명 변경

추가로 해본것
- 네트워크 오프라인일때, 무한스크롤하면 계속 다음페이지 fetch시도하던 문제 해결
-  기존에 실패했던 테스트코드 3개 모두해결
> 이 테스트 코드를 실행해보면,
20개가 불러와진 다음에, 24개가 아니라, 3000개 가량이 불러와 지는데요.
4개씩불러오는 로직이 수백번 실행되는 현상입니다.
> 비동기 API요청에대해 테스트 해봤는데,
작성한 비동기테스트들 중 일부가 정상동작하지 않아 우선 해당테스트는 주석처리해놓은 상태입니다
( 비동기 테스트에 대해 의문스럽던 문제점들 모두 이해/해결 완료 )

- 영문 문구이던 카테고리 드롭 다운을 한글로 보이게 변경
봐주셔서 감사합니다 :)

2024-06-06 07:20 UTC, JeongBin0227 commented on src/utils/productSorter.ts
> +    }
네 맞습니다! 리버스가 된다는 말이였습니다

2024-06-06 07:20 UTC, JeongBin0227 commented on src/utils/productSorter.ts
> +  const products = [...productCopy.content];
네 맞습니다 👍

2024-06-06 07:33 UTC, JeongBin0227 approved these changes
안녕하세요 제이드!

수정해주신 코드 확인했습니다 👍 추가로 몇 코멘트 남겨드렸으니 읽어보시면 좋을거 같고, 추가로 남겨주신 코드에 대해서는 다음 리뷰에 같이 확인해보겠습니다

1단계 미션 고생하셨습니다~ 2단계에서 만나요

2024-06-06 07:33 UTC, JeongBin0227 commented on src/hooks/useFetchProducts.test.ts
> +  // });
제가 직접 돌려봐야하는데 그게 여의치 않아, 코드를 보면서 추측해보면
1. fetchNextPage 함수가  상태를 업데이트할 때마다 컴포넌트가 다시 렌더링되고, 그로 인해 상태 업데이트가 다시 트리거되고... 이러면서 무한루프가 생기지 않을까 생각합니다. 

```

코드 복사
const { result } = renderHook(() => useFetchProducts());

await waitFor(() => {
  expect(result.current.products).toHaveLength(20);
});

await act(async () => {
  await result.current.fetchNextPage();
});

await waitFor(() => {
  expect(result.current.products).toHaveLength(24);
});
```
요런식으로 변경해봐도 동일할까요?

2024-06-06 07:33 UTC, merged