[1단계 - 상품 목록] 다르(이상엽) 미션 제출합니다.
woowacourse/react-shopping-products pull request #23
Opened 2024-05-30 08:35 UTC by pp449

앱 링크 : [배포주소](http://react-product-darr.s3-website.ap-northeast-2.amazonaws.com)

서버가 http 프로토콜로 구축되어 있는 관계로 클라이언트에서 확인하기 편하게 하기위해 AWS S3 로 배포했습니다! 

---

안녕하세요 호프 처음뵙겠습니다 😄 항상 다른 크루들의 리뷰를 훔쳐(?) 볼 때 호프가 리뷰를 꼼꼼하게 잘 해주시는 모습을 보고 저도 호프에게 리뷰 받아보고 싶었는데 이번에 이루어지게 됐네요..! ㅎㅎㅎ

다른 크루의 PR 본문을 봤을 때 건강 이슈가 있다는 글을 봤었는데 지금은 괜찮으신가요..? 
얼른 쾌차하셨으면 좋겠습니다! 💪💪

리뷰 전 백그라운드를 알려드리자면 react, msw 기술을 모두 사용해봤기에 기술적인 어려움은 없었어요.
그리고 상처를 잘 받지 않는 성격이어서 날카롭게 질문해주셔도 좋습니다!

# 🎨 컴포넌트 구성

<img width="540" alt="스크린샷 2024-05-28 오후 5 38 46" src="https://github.com/woowacourse/react-shopping-products/assets/125418818/5db6b6d1-4d9b-45ab-b6f6-f1a1590c8203">

## 🔑 서버 데이터의 동일한 key 문제 (참고사항)
서버에서 `Products` 를 get 으로 받아오게 되는 경우 동일한 아이템을 가져오는 경우도 있어요

개인적으로 예상하기로 동일한 금액의 아이템으로 정렬을 했지만 추가적인 정렬을 하지 않아서 그런거 같아요!
(아마 sql query 로 item price 로 sort 시 price 이외의 순서는 보장하지 않아서 그런거 같아요)

그래서 요청할 때마다 동일한 금액의 아이템은 랜덤으로 가져오기에 중복된 아이템을 가져오는 경우도 있는거 같아요

# 🙋‍♂️ 궁금한 점

### 테스트코드 작성
테스트코드는 기능구현 외적으로 추가 리소스를 사용하는 것이기에 생각했을 때 필요한 테스트코드를 작성하는게 좋다고 생각합니다.

현재 테스트코드가 거의 없기는 한데 어떤 테스트가 추가되어야 하는지 잘 모르겠어요..
(개인적으로 UI 테스트, 함수 호출 시 setState 가 잘 되는지 테스트는 의미가 없는 테스트라는 생각이 들어요..)

그래서 어떤 테스트가 더 추가되면 좋은지 궁금합니다!

### MSW 에 대한 생각
우선 저희는 브라우저, 서버 모두 MSW 를 사용했어요

브라우저단에서 MSW 를 이용하여 네트워크 요청을 가로채어 Mock data 를 반환하는 건 매우 유용하고 큰 의미가 있다고 생각해요.
하지만 서버 (테스트) 에서 MSW 를 지원하게 되었을 때 장점을 못찾았어요..

그 이유는 MSW 를 이용하여 특정 요청에 대해 mock data 를 반환해주는 역할을 하는데 그 역할은 jest 에서 함수 자체를 모킹을 시킨다면 충분히 필요한 데이터를 받아와 사용할 수 있다고 생각했어요. 
호프가 생각하기에 MSW 를 서버에서 사용했을 때 jest 의 mock 을 이용한거에 비해 어떤 장점이 있다고 생각하는지 궁금해요!

### MSW 기능 구현 범위
위의 질문과 비슷한 질문일수도 있는데 MSW 내부 핸들러 로직에 복잡한 로직 처리를 만드는게 좋을까 궁금합니다!

이렇게 생각한 이유는 위에서 언급했듯이 테스트 자체로 추가 리소스를 사용하기에 어렵고 복잡하게 쓰는게 좋은 방법은 아닌거 같아요..
그리고 msw 의 로직을 만든다 해도 서버와 동일한 동작을 흉내내기는 힘든 부분도 많다고 생각하기에 복잡하게 핸들러를 구축하기 힘들다고 생각해요!

예를들어 `카트 아이템 추가` 후 `카트 아이템 리스트 조회` 하게 된다면 추가된 카트 아이템을 조회하는거는 핸들러에서 처리하기 힘들기에 해당 테스트는 하지 않았어요

호프가 생각하기에 MSW 의 핸들러 기능은 어느정도로 만드는게 적절하다고 생각하나요 ??

2024-05-30 15:25 UTC, moonheekim0118 requested changes
안녕하세요, 다르~ 만나서 반갑습니다 :) 이번 미션동안 잘 부탁드려요!
제 건강 걱정도 해주셔서 감사해요 다행히 괜찮습니다ㅎㅎ 😌

## Q&A
### 1. 테스트코드 작성

> 테스트코드는 기능구현 외적으로 추가 리소스를 사용하는 것이기에 생각했을 때 필요한 테스트코드를 작성하는게 좋다고 생각합니다.

저도 동의합니다. 저 역시도 테스트 대상은 '이 동작이 돌아가지 않으면 크리티컬하다!'하는 것에 테스트코드를 주로 작성하게 되는 것 같아요.
하지만 UI테스트는 멀리 봤을 때 생산성을 향상시켜줄 수 있다는 점에서 유의미 할 수 있다고 생각이 들구요, 
다르가 말씀해주신 것 처럼 저 역시도 단순히 setState 호출과 같은 라이브러리의 API 로직을 테스트하는건 무의미하다고 생각하는 편입니다.

현재 요구사항에서 더 추가해볼만한 테스트는

상품 목록 조회 기능에서
- 필터 변경 시 요청을 잘 하는지 (카테고리, 정렬 각각)

장바구니 담기 기능에서
- 장바구니 추가/삭제에 따른 장바구니 count 변경

이 정도가 되겠네요.
사실상 현재 어플리케이션에서 가장 중요한건 비동기 요청이기 때문에 요 부분에 대한 테스트를 더 추가해주시면 좋지않을까~~생각합니다 ㅎㅎ

### 2. MSW 에 대한 생각
저는 일단..
1. 테스트에서 별도로 모킹을 관리하지 않아도 되어서 좋다고 생각하고
2. msw 에서 제공해주는 메서드를 사용해 다양한 서버 응답값(에러처리, 상태코드 처리 등등)들을 비교적 간단히(?)모킹 할 수 있어서 좋다고 생각해요.


### 3. MSW 기능 구현 범위
먼저 msw 를 사용하는 이유에 대해서 고민해보면 좋을 것 같은데요!
msw 를 붙이는 이유는, 서버의 동작을 100% 똑같이 프론트엔드에서 모킹하기 위함이 아니라,
서버와의 통신 과정(요청 성공, 요청 실패, 데이터 응답)을 모킹하기 위함이라고 생각해요. 추후에 실서버를 붙일 때 편하도록요.

따라서 말씀주셨던 것 처럼 다소 복잡한 로직들은 굳이 구현을 하지 않아도 된다고 생각합니다ㅎㅎ
예를들어

- 카트 아이템 추가 핸들러
- 카트 아이템 조회 핸들러

두가지가 있어도 이 두개가 굳이 실제 서버처럼 동작이 연결시킬 필요까진 없다고 생각합니다.
그냥 각각의 올바른 형태의 응답만 반환해줘도 충분하다고 생각해요.


그럼 고생하셨어요 다르! 천천히 코멘트 확인 후 재요청 주세요 😄

2024-05-30 15:25 UTC, moonheekim0118 commented on src/pages/ProductListPage/index.tsx
> +  const isAbleFetchNextPage = !loading && !isLastPage;
isAbleFetchNextPage도 useProducts 훅에서 관리해주면 좋지 않을까요?

2024-05-30 15:25 UTC, moonheekim0118 commented on src/provider/cartItemProvider.tsx
> +  }, []);
요 부분도 훅으로 분리해보면 어떨까요?

2024-05-30 15:25 UTC, moonheekim0118 commented on src/hooks/useHandleCartItem.test.tsx
> +  it("장바구니에 있는 아이템 빼기 버튼을 누르면 장바구니에서 제거된다.", async () => {
장바구니 추가하기는 없나요~?

2024-06-01 19:01 UTC, pp449 reviewed
안녕하세요 호프 꼼꼼한 리뷰 덕분에 많은 고민을 해보고 적용해볼 수 있었어요! 😄

지금 일부 피드백에 대해선 반영하지 못했지만 호프가 접근방법만 조금 도와준다면 해결해보도록 하겠습니다

아직 부족한 점이 많겠지만 이번에도 잘 부탁드려요 호프 🙇‍♂️🙇‍♂️

피드백 반영된 사항까지 모두 위에 언급한 배포 주소에도 반영 완료했습니당 🫡

# 질문사항
### 이미지 파일 위치
이미지 파일을 `src 내부`에 넣을수도 있고 `public` 에 배치할 수도 있는데 호프는 어디에 넣는것을 선호하시나요 ??

`src 내부` 에 배치하게 된다면 번들링 처리를 하게 되며 어느 정도 크기 최적화를 할 수 있는걸로 알고 있고, `public` 에 배치하게 된다면 해당 파일들은 빌드 시 번들링을 하지않고 파일 그대로 `dist` 에 배치되는 걸로 알고있어요!

그렇다면 단편적으로 본다면 항상 `src 내부` 에 배치하는게 좋아보이는데 대부분의 경우도 `src 내부` 에 이미지 파일들을 배치시키는지 궁금합니다!

2024-06-01 19:05 UTC, pp449 commented on src/hooks/useProducts.ts
> +    page === 0 ? setProducts(res.content) : setProducts((prevProducts) => [...prevProducts, ...res.content]);
요기 코드의 가독성에 고민을 했는데 호프가 보기에 괜찮나요 ??

2024-06-02 03:37 UTC, pp449 commented
안녕하세요 호프 혹시나 리뷰중이시라면 죄송합니다..!

현재 배포된 주소에서 (재미로) 저번 미션이었던 `장바구니` 를 물리적으로 연결시켜봤어요!
그래서 장바구니 클릭하면 장바구니 페이지로 이동할 수 있도록 해봤어요

혹시나 리뷰중에 추가 커밋이 있으면 불편하실수도 있으니 해당 내용은 커밋 추가를 하지 않았지만

배포된 프로덕션의 변경된 내용은 `window.location.href` 추가된 것 밖에 없습니다!

2024-06-02 15:29 UTC, moonheekim0118 commented on src/apis/product.ts
> +  searchParams.append("sort", `price,id,${convertedSort}`);
아하 설명 감사합니다ㅎㅎ 👍

2024-06-02 15:29 UTC, moonheekim0118 commented on src/apis/product.ts
> +  const convertedSort = SORT[sort];
척하면 척이시군요ㅎㅎ 좋습니다 👍 👍

2024-06-02 15:30 UTC, moonheekim0118 commented on src/apis/product.ts
> +  const response = await fetch(SERVER_URL.apiUrl + END_POINT.products + "?" + searchParams.toString());
굿굿 좋습니다 ㅎㅎ 딱적당한 사이즈로 만들어봐주신 것 같아요. 👏

2024-06-02 15:32 UTC, moonheekim0118 commented on src/components/ItemCardList/index.tsx
> +      {products && products.map((product) => <ItemCard key={Math.random() * 10000} product={product} />)}
너무 귀엽네요 😆 🦦

2024-06-02 15:45 UTC, moonheekim0118 commented on src/components/_common/Toasts/Toast/index.tsx
> +    }, 500);
아하, 이미 고민해보셨군요? 도출된 이유가 좋네요 👍 👍 

저도 다시 생각해보니 다르 말씀처럼 하나의 앱 내에서 토스트 지속시간은 동일한게 사용자 경험상 좋을 것 같기도하고, 제 경험에도 지속시간이 다른 경우는 거의 없어서 지금처럼 유지해도 좋을 것 같아요! ㅎㅎ 

다만 지속시간은 컴포넌트 내에서 상수로 관리해주면 좋겠죠?ㅎㅎ

2024-06-02 16:04 UTC, moonheekim0118 commented on src/components/_common/Toasts/Toasts.tsx
음..일단 아마 2번째가 제가 생각했던 방향인 것 같은데요. 저는 아래와 같은 방법을 생각했습니다. 정확히 말씀드리자면 일부분만 Context 전역상태 사용 + Portal 사용 방법이었어요. 다르가 말씀주신대로 전역상태를 사용하지 않을 경우에는 제한사항이 있기때문이겠죠?

요건 말씀으로 설명드리는 것 보다 코드로 설명드리는게 간결할 것 같아서 간단하게 예시를 작성해봤는데요 이게 정답은 아니니, 참고만 해주세요.

1.  index.html 파일이 아래와 같이 됩니다.
```html
<html>
  <body>
    <div id="app-root"></div>
    <div id="toast-root"></div>
  </body>
</html>
```

2. Toast 컴포넌트는 아래와 같이 선언되고, app.tsx 하단에 추가됩니다. 이 때 전역상태를 사용해야하므로 Provider 로 감싸주고요.
```tsx
const App = () => { 
   return <div>
   //.. 생략
   <ToastProvider>
       <Toast/>
   </ToastProvider>
   </div>
}
```

3. 위에서 선언한 Toast 컴포넌트는 아래와 같을 것 같구요 
```tsx

const Toast = ()=> {
  const { isOpend, message }  = useContext(ToastStateContext);

  const root = document.querySelector('#modal-root');

  return isOpend && root
    ? ReactDOM.createPortal(
        <S.Toast>
           {message}
        </S.Toast>,
        root
      )
    : null
}
```

4. useToast 훅은 상상이 가실 것 같아서 생략합니다 ㅎㅎ 여기선 오로지 message 랑 isOpened 상태만 관리하는거죠.

제가 뭔가 전역상태를 사용하지 말라! 라고 말씀드린 것 처럼 오해하실 수 있었겠네요 💦 명확히 말씀드리지 못해서 죄송합니다 🙏 
정확히 말씀드리자면 전역상태에 '토스트 목록'이 관리되는것에 대해 아쉬움에 남긴 코멘트였슴니다ㅎㅎ

2024-06-02 16:06 UTC, moonheekim0118 commented on src/components/_common/Toasts/Toasts.tsx
추가로 portal 을 사용하지 않고도 위의 방법대로 구현해도 문제 없겠죠? 
그런데 왜 요런 모달 UI 구현 시 portal 을 사용하는 경우가 많을까요? 요걸 한번 고민해봐주시면 좋을 것 같아요.

다르가 생각하시기에 현재 다르의 서비스에서는 굳이 portal 을 도입하지 않아도 될만한 사이즈라고 생각하시면, portal 없이 구현하는 방향을 선택하셔두 좋구요.

2024-06-02 16:08 UTC, moonheekim0118 commented on src/components/_common/Toasts/Toasts.tsx
> +      ))}
요건 위의 코멘트로 설명 가능할 것 같아요!

훅 사용방법은ㅎㅎ맞아요..현재도 그렇게 되어있어서 혼란스러우셨겠군요 🙏 요것도 결국 전역상태에 토스트목록이 관리되는 아쉬움에 남긴 말씀이었습니다 😓

2024-06-02 16:09 UTC, moonheekim0118 commented on src/hooks/useHandleCartItem.ts
> +      const fetchedItems = await getCartItems();
와우 좋습니다 👍 👍 너무 잘 개선해주셨네요 👏

2024-06-02 16:17 UTC, moonheekim0118 commented on src/hooks/useHandleCartItem.ts
> +  return { onClickCartItem, isInCart, loading };
현재는 아래와 같이 isInCart 여부에 따라서 추가 혹은 삭제를 해주고 계신데요,
```tsx
  const onClickCartItem = (id: number) => {
    if (isInCart(id)) onDeleteCartItem(id);
    else onAddCartItem(id);
  };
```
요거는 토글기능에 가까운 것 같아요.

그런데 만약에 아래와 같은 UI로 현재 장바구니에 이미 아이템이 추가되었어도, 또 다시 아이템을 추가할 수 있도록 UI 가 변경되면 어떡할지에 대해 말씀드린 거였어요.

이러한 상황에 대비하기 위해서는 추가 / 삭제 함수를 각각 반환하고 이를 사용처(UI 레이어) 에서 판단하여 호출하는게 좋지 않을까 생각했습니다.

https://github.com/woowacourse/react-shopping-products/assets/61469664/17a637cc-0f91-4929-84d4-fe378a7ebf4d



그리고 API 스펙 변경에 대해서 말씀주셨는데요,
그러면 다르 말씀대로라면 UI 가 변경될 때 마다 API 스펙이 변경되어야할 것 같아요. 물론 API 스펙 역시 디자인의 영향을 많이 받기도 하지만, 이런 사소한 UI 변경 같은 경우는 대응하는 영역이 프론트엔드로만 한정되는게 베스트입니다. UI 는 프론트엔드의 책임이니까요?ㅎㅎ UI 가 바뀔 때 마다 API 스펙이 변경되면 프/백 둘다 괴롭겠죠..? 😭

따라서 이런 UI 확장성들을 잘 고려하셔서 개발해주시는게 좋습니다.

2024-06-02 16:25 UTC, moonheekim0118 commented on src/hooks/useInfiniteScroll.ts
> 정확히는 어떻게 트리거를 일으켜서 원하는 처리를 할 수 있을지 모르겠는데

혹시 ref 를 어디에 주입해줘야할지에 관한 질문이실까요?.?
저라면..두가지의 선택안이 있을 것 같은데요
1. children 영역을 div 로 감싸고 해당 div 에 ref 주입
```tsx
<div ref={targetRef}>{children}</div>
```

2. children 영역 하위에 빈 div 태그를 하나 둬서 해당 div 에 ref 주입
```tsx
<>
   {children}
   <div ref={targetRef}/>
</>
```

요런 방법이 있을 것 같은데..요것도 정답은 아닙니다 ㅎㅎ; 저도 간략하게 생각해본거라 정확히 구현시에는 어떨지 모르겠네요ㅎㅎ

2024-06-02 16:46 UTC, moonheekim0118 requested changes
안녕하세요, 다르! 반영해주신 사항 모두 확인했습니다 👏 👏 

남겨주신 질문에 답변 달아두었어요, 혹시나 추가로 이해안되시는 부분이 있다면 추가 코멘트 남겨주시면 확인할게요. 🙂 

> 이미지 파일 위치

차이를 잘 알고 계시네요 😮  👏 👏 
때에 따라 다른 것 같은데..저는 경험상 컴포넌트 내에서 사용이 필요한 경우는 src 내부에 배치하고, 그게 아닌 경우에만 public 하위에 두었던 것 같네요! (ex. 파비콘 이미지)

src 내부에 위치하면..해당 경로가 없을 경우 컴파일 단계에서 오류를 뱉으니까 미리 이미지 엑박(?)에러를 방지 할 수도 있을 것 같고요!


그럼 고생하셨어요 다르 🦦 코멘트 남긴 사항에 대해서 아마 더 이야기 나누고 싶으실 것 같아서 한번 더 rc 드립니다. 확인 후 재요청 주시면, 그 때 머지할게요!

2024-06-02 16:46 UTC, moonheekim0118 commented on src/components/ItemCardList/index.tsx
> +        products.map((product) => <ItemCard key={Math.random() * 10000} product={product} />)
```ts
Math.random() * 10000
```

요건 유니크한 키값 주입을 위해서 추가해주신걸까요~?
productId 만으로 유니크함이 보장되지 않는다면 

`product Id + index`
요런 조합으로 사용해볼 수도 있고

혹은 uuid, cuid 등을 사용하는 경우가 많은 것 같아요.

2024-06-02 16:46 UTC, moonheekim0118 commented on src/components/ItemCardList/index.tsx
> +        products.map((product) => <ItemCard key={Math.random() * 10000} product={product} />)
추가로..논외이긴 하지만 자바스크립트의 Math.random 함수에 관한 재미있는 글이 있어서 공유해봐욘

- [자바스크립트에서 안전하게 난수 생성하는 방법](https://yceffort.kr/2021/09/javascript-random-number#%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EC%97%90%EC%84%9C-mathrandom%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EA%B2%BD%EC%9A%B0)

2024-06-02 16:46 UTC, moonheekim0118 commented on src/hooks/useProducts.ts
> +    page === 0 ? setProducts(res.content) : setProducts((prevProducts) => [...prevProducts, ...res.content]);
아하 확실히 가독성이 조금 떨어지긴 하네요? 
아래 응답값에 따라서 lastPage 상태나, products 상태, currentPage 상태를 변경해주는 부분이 따로 함수로 분리되어 관리되면 더 좋겠네요 ㅎㅎ fetch 와는 엄연히 다른 역할을 하고 있으니까요?

2024-06-04 02:09 UTC, pp449 commented on src/components/_common/Toasts/Toasts.tsx
여러가지 시도 끝에 다양한 방법으로 Toast UI 를 만들 수 있다는 것을 알게됐어요 !

> 1. 전역 상태로 관리되는 toast UI 를 createPortal 로 원하는 엘리먼트로 이동시킨다
> 2. 지역 상태로 toast UI 를 만든 후 createPortal 로 원하는 엘리먼트로 이동시킨다

우선 제가 언급했던 2가지 방식에 대해서인데 

2번의 경우에도 `createPortal` 을 이용하여 토스트 UI 를 만들 수 있었어요

예를 들어
``` tsx
import Toast from ".../toast";

const ComponentA = () => {
  .....
  return <>
    ......
    {isOpenToast && <Toast message="메시지" />}
  </>
}
```

요런식으로 UI 레이어에서 `Toast` 컴포넌트를 호출하게 되고, `Toast` 컴포넌트에서 createPortal 을 이용해 상위 노드로 올려주는 방법이 있었어요!

하지만 해당 방법을 이용한다면 UI 레이어에서만 `Toast` 컴포넌트를 호출할 수 있기에 도메인 로직 (예를 들어 데이터 패칭 실패 시) 토스트 메시지를 보여주는게 어렵다는 문제가 있었어요!

그렇기에 1 의 방법으로 전역 상태관리가 있어야지만 활용도 높게 `Toast` 를 만들 수 있다고 생각했어요

---

그렇다면 만든 토스트와 호프가 언급해준 토스트 UI 둘 다 전역 상태관리를 이용하는 1의 방식일건데요.

사실 제가 사용했던 토스트 UI 와 호프가 예시로 들어준 토스트 UI 의 차이는 없는거 같아요!

우선 그렇게 생각한 이유는 호프가 예시로 들어준 코드를 보면 `Provider` 를 사용하며 `Toast` 컴포넌트가 App 파일 (리액트 DOM 중 거의 시작 노드) 에 있는 것을 확인할 수 있어요

`createPortal` 을 이용하여 원래 App 에서 렌더링 될 토스트 UI 를 조금 더 상위의 노드로 이동시키는 차이일 뿐이지 로직의 차이는 없다는 생각이 들었어요! (혹시 제가 잘못 이해한거라면 코멘트 부탁드립니당..)

하지만 코드의 일부 차이가 있는데 그 이유는 호프가 들어준 예시는 `Toast` 1개 렌더링에 대한 로직이고, 제가 작성한 로직은 여러개의 `Toast` 를 렌더링 할 수 있도록 한 차이인거 같아요!

사진으로 예시를 든다면 아마 호프가 알려준 예시는 최대 1개의 토스트만 뛰어줄 수 있으나 저의 경우는 아래와 같이 여러개의 토스트 메시지를 보여줄 수 있게한 차이인거 같아요 !
<img width="1840" alt="image" src="https://github.com/woowacourse/react-shopping-products/assets/71641127/b1166bb7-bb48-4ca5-bab5-398f72c884a8">

2024-06-04 02:29 UTC, pp449 commented on src/components/_common/Toasts/Toasts.tsx
우선 `createPortal` 을 사용하여 리팩토링을 진행해봤어요!

Toasts 컴포넌트에서 JSX 로 Toast 컴포넌트들을 단순히 반환하는 대신 `createPortal` 을 사용하도록 했어요

사실 지금 당장의 렌더링 성능의 향상이나 
당장의 `z-index` 문제 해결되는 이점은 없었어요 (이미 React DOM의 거의 상위 노드에 Toast 컴포넌트를 렌더링 하기 때문)

하지만 createPortal 을 이용한다면 
React DOM 외부에 컴포넌트를 삽입하여 리액트와 독립적으로 렌더링이 가능하여 
만약 createPortal 을 사용하지 않았을 때 토스트 UI 상위의 컴포넌트가 렌더링이 되며 토스트 UI 도 같이 렌더링 되는 문제를 해결할 수 있을거 같아요!

> 추가적으로 알게된 사항
index.html 파일에 `<div id="root"></div>` 이 있는데 `<div id="root"><div id="toast-root"></div></div>` 이런 식으로 root 하위에 엘리먼트를 배치하게 되면 정상적으로 `createPortal` 을 사용하지 못한다는 것을 하게되었어요

그 이유는 `ReactDOM.createRoot(document.getElementById("root")!).render ...` 해당 코드에서 id 가 root 인 태그를 가져와 React 로 렌더링 하기에 `<div id="toast-root"></div>` 엘리먼트가 없어지는 (정확히는 리액트 컴포넌트로 대체되는) 것을 확인할 수 있었어요

[관련 커밋](https://github.com/woowacourse/react-shopping-products/pull/23/commits/89bc353c35c6471b1d22496c08c9a548f9a0f0de)

2024-06-04 05:28 UTC, pp449 commented on src/hooks/useHandleCartItem.ts
> +  return { onClickCartItem, isInCart, loading };
아하 최대한 UI 의 확장성을 고려하여 개발하는것에 대해 호프의 의견에 동의합니다!

> 이러한 상황에 대비하기 위해서는 추가 / 삭제 함수를 각각 반환하고 이를 사용처(UI 레이어) 에서 판단하여 호출하는게 좋지 않을까 생각했습니다ㅎㅎ (혹은 저 토글 함수(onClickCartItem)는 그대로 두고 addCart, deleteCart 를 추가로 반환해주는 방법도 있겠지요?)

UI 레이어에서 직접 원하는 함수를 호출하는 것도 좋지만 개인적으로 `어떤 함수를 호출할지 판단` 하는 것도 UI 책임보다는 도메인 로직의 책임에 가깝다 생각하여 저는 커스텀 훅에서 처리하는게 좋은거 같아요 !

2024-06-04 06:21 UTC, pp449 commented on src/hooks/useInfiniteScroll.ts
아하 호프가 알려준 2번째 방법을 이용하여 `InfiniteScroll` 컴포넌트를 만들어줬어요!

현재 상품을 불러오는 로직 이외에도 추후 재사용성을 위해 데이터 패칭 함수, 마지막 페이지인지 확인하는 boolean 2가지를 인수로 받아 처리하도록 했어요

혹시 함수의 인자와 활용이 적절한지 궁금합니당

[관련 커밋](https://github.com/woowacourse/react-shopping-products/pull/23/commits/4d3cd29df6d4cf6b9d66ba2a51049a3ad5298f8d)

2024-06-04 07:20 UTC, pp449 commented on src/hooks/useProducts.ts
> +    page === 0 ? setProducts(res.content) : setProducts((prevProducts) => [...prevProducts, ...res.content]);
```suggestion
setProducts((prevProducts) => (page === 0 ? res.content : [...prevProducts, ...res.content]));
```

우선 해당 코드가 최선이라 생각하여 변경했습니다!

2024-06-04 07:25 UTC, pp449 commented
안녕하세요 호프 😄

덕분에 createPortal 에 대해 더 공부해볼 수 있었고, 어떻게 활용해볼 수 있을지 고민해볼 수 있는 시간이 되었어요!
조금은 고정된 사고를 유연하게 볼 수 있는 시야를 가지게 된거 같고 많이 배울 수 있었어요

빠르게 머지 안해주셔도 git 을 이용하여 충분히 step2 미션을 진행할 수 있기에 호프 여유로울 때 천천히 확인해주셔도 됩니당

2024-06-04 12:01 UTC, moonheekim0118 approved these changes
안녕하세요 다르! 남겨주신 코멘트와, 변경된 사항 확인했습니다. 👏 👏 
제가 인지하지 못했던 부분에 대해서 친절하게 설명해주셔서 정말 감사해요 ☺️

그럼 이만 다음 단계로 넘어가시지요~!  끝까지 고생많으셨습니다!
다음 단계도 기대하고 있을게요 :)

2024-06-04 12:01 UTC, merged