[1단계 - 상품 목록] 마스터위(명재위) 미션 제출합니다.
woowacourse/react-shopping-products pull request #26
Opened 2024-05-30 08:42 UTC by Jaymyong66

안녕하세요 브콜!

레벨 2 마지막 미션으로 뵙게 되어 반갑습니다. 잘 부탁드립니다!

2024-05-30 09:00 UTC, Jaymyong66 commented on src/hooks/useCartItems.ts
> +  }, [cartItems]);
상품을 카트에 추가하는 POST 요청에서는 상품의 ID를 params로 보냈지만, 해당 상품을 카트에서 제거할 때는 장바구니의 ID가 필요했습니다.
따라서 상품의 ID와 장바구니 ID의 매핑을 만들고자 하였습니다. 
괜찮은 방법인지 궁금하고, API가 이럴 경우 혹시 어떻게 대처해야하는지 궁금하네요..! ㅎㅎ
POST 요청 시, 들어간 장바구니의 ID를 반환해주면 좋을텐데요!
```tsx
export type ProductType = {
  id: number;
  name: string;
  price: number;
  imageUrl: string;
  category: string;
};

export type CartItemType = {
  id: number;
  quantity: number;
  product: ProductType;
};
```

2024-05-30 09:01 UTC, Jaymyong66 commented on src/hooks/useProducts.ts
> +  }, []);
다음 부분에서 react strict 모드라 초기 데이터가 20개가 아닌 40개가 오는 이슈가 있었습니다.
배포 페이지에서는 문제가 없었는데, 이런 경우 어떻게 개발하시는지 궁금합니다.

2024-05-30 09:21 UTC, Jaymyong66 commented on src/hooks/useProductSelection.ts
> +  };
장바구니에 담기, 뺴기 버튼의 로직입니다. 요청이 성공 후 UI가 업데이트 되어 흔히 말하는 낙관적 업데이트는 구현되지 않은 상태입니다. 
또 마지막의 getCartItems 비동기 요청으로 상품 ID에 대한 장바구니 ID를 가져오고, 장바구니의 갯수 UI를 업데이트 합니다.

2024-05-31 18:24 UTC, Tanney-102 requested changes
안녕하세요 마스터위~!
미션 진행하느라 고생 많으셨습니다!
말씀하신 훅 관련 및 참고하실만한 내용 코멘트 남겨두었습니다.
테스트 코드도 올려주시면 확인할게요!

2024-05-31 18:24 UTC, Tanney-102 commented on src/context/ToastProvider.tsx
> +    }, 3000);
toast 지속 시간을 prop으로 받으면 어떨까요?

2024-05-31 18:24 UTC, Tanney-102 commented on src/hooks/useCartItems.ts
> +  const [idMap, setIdMap] = useState<Record<number, number>>({});
```suggestion
export function useCartItems() {
  const [cartItems, setCartItems] = useState<CartItemType[]>([]);
  const [idMap, setIdMap] = useState<Record<ProductType['id'], CartItemType['id']>>({});
```

어떤 id를 어떤 id에 맵핑하는 건지 명시해주면 더 이해하기 좋을 듯 합니다.

2024-05-31 18:24 UTC, Tanney-102 commented on src/hooks/useCartItems.ts
> +    setIdMap(newIdMap);
이전 상태를 참조해 업데이트할 때는 setState에 콜백으로 넣어주세요

2024-05-31 18:24 UTC, Tanney-102 commented on src/hooks/useCartItems.ts
> +  }, [cartItems]);
말씀하신것처럼 서버에서 해주면 가장 좋구요!
id를 맵핑하는 방법 아주 좋습니다 👍

2024-05-31 18:24 UTC, Tanney-102 commented on src/hooks/useCartItems.ts
> +      showToast(ERROR.addProduct);
이 훅은 domain으로 보이는데 view에서 해야하는 일을 하고 있군요

2024-05-31 18:24 UTC, Tanney-102 commented on src/hooks/useCartItems.ts
> +  }, [cartItems]);
cartItems에 대한 effect를 만들기보다 그냥 cartItem을 fetch하는 시점에 직접 idMap을 업데이트 하면 어떨까요?

2024-05-31 18:24 UTC, Tanney-102 commented on src/hooks/useInfinityScroll.ts
> +    [hasMore, setPage],
이름은 useInfinityScroll로 추상적인데 내부 구현은 아주 구체적이군요..!
이 훅이 product, page 이런 도메인 지식을 모르도록 할 수 있을까요?

2024-05-31 18:24 UTC, Tanney-102 commented on src/hooks/useProductFetch.ts
> +            : FIRST_FETCH_SIZE / AFTER_FETCH_SIZE - 1 + page;
이런 기획을 갖게된 이유가 있을까요?
또 이 코드 입장에서 FIRST_FETCH_SIZE / AFTER_FETCH_SIZE 가 정수라는 보장이 없을 것 같은데 괜찮은 걸까요?

2024-05-31 18:24 UTC, Tanney-102 commented on src/hooks/useProducts.ts
> +  }, []);
react query 같은 애들을 쓰면 사실 알아서 해줘서 신경을 잘 안쓰긴하는데요~
async 함수를 effect에서 호출하는 훅을 따로 만들고 그 안에서 dev mode일 때는 effect가 한 번만 돌도록 제어하면 어떨까 싶습니다.

2024-06-05 10:03 UTC, Jaymyong66 reviewed
안녕하세요 브콜!
피드백 및 테스트 코드 반영을 완료하여 리뷰요청 드립니다!

피드백에 관련한 반영사항은 코멘트로 남겼습니다!

`mocks` 폴더의 handler.ts와  `hooks/test`폴더의 테스트 파일 위주로 봐주시면 감사하겠습니다!

### 실행방법
[피드백 반영 후 배포 주소](https://jaymyong66.github.io/react-shopping-products/dist/)

- 로컬 실행
.env 파일은 동일합니다.
```bash
npm install
npm run dev
```

### 질문 사항
- mock 데이터 테스트 관련
예를 들어 장바구니 정렬 query가 포함된 요청을 해보겠습니다. 이를 테스트 하기 위해 
1. handler 함수에서 전체 products 데이터를 정렬해서 반환하기
2. handler 함수에서 이미 정렬되어 있는 sortedProducts 데이터를 반환하기

두가지 방법이 있지 않을까? 생각했습니다.
2번과 같은 방법을 생각한 이유는 만약 서버와 정렬 로직이 다르거나 옵션이 추가된다면 프론트엔드에서 해당 로직과 비슷하게 구현을 해야했던 것 같습니다.

보통은 어떤 방식으로 테스트를 활용하시는지 궁금합니다.

---

추가적으로 피드백 주신다면 반영해보겠습니다!
감사합니다.

2024-06-06 16:23 UTC, Tanney-102 commented on src/hooks/useProductFetch.ts
> +            : FIRST_FETCH_SIZE / AFTER_FETCH_SIZE - 1 + page;
네 맞아요 이런 기획은 얼마든지 바뀔 수 있을 것 같은데 더 나은 방식은 없을지 궁금했어요!

2024-06-06 16:26 UTC, Tanney-102 commented on src/hooks/useCartItems.ts
> +    setIdMap(newIdMap);
정확합니다 👍

2024-06-06 16:31 UTC, Tanney-102 commented on src/hooks/useCartItems.ts
> +      showToast(ERROR.addProduct);
1. 에러를 상태로 두어도 좋지만 에러가 발생한 당시에 토스트를 보여주거나 하는 동작은 reject된 promise를 catch하는 방식이 더 편리해 보이네요~!
2. context를 사용하고 말고는 관련 없습니다~ 해당 훅의 사용처에서 토스트로 에러를 보여주든 모달로 보여주든 이 훅에서 알 필요가 없다는 뜻이었습니다. 레벨1에서 도메인과 UI를 나눴던 기억을 다시 떠올려보시면 좋겠습니다.

2024-06-06 16:32 UTC, Tanney-102 approved these changes
안녕하세요 마스터위~!
꼼꼼하게 잘 반영해주셔서 감사해요!
useCartItem 에러처리 관련 reply 하나 남겨두었으니 다음 스텝 진행하시면서 고민해보시면 좋겠습니다! 추가 질문 있으시면 DM 주셔도 좋을 듯 해요! PR 코멘트 노티는 놓치기 쉬워서..!

2024-06-06 16:32 UTC, merged