Step1
woowacourse/react-shopping-products pull request #31
Opened 2024-05-30 08:50 UTC by dle234

안녕하세요 블링! 마지막 미션 리뷰 잘 부탁드려요!!😊
서버에서 불러오는 데이터가 기본 사이즈가 4 라서 아이템을 4개씩 불러와서 

## 구조
### custom hooks
- useCartItems 
- useDropdown
- useProductList

### components
![Frame 18357](https://github.com/woowacourse/react-shopping-products/assets/108859281/145c9cb1-1b6c-4121-b3cf-007d6e6ca241)

## 이번 미션에서 중요하게 생각한 부분 
### MSW 
- product item 을 불러올 때 msw 로 데이터를 넣어주었습니다.
- handler 로 마지막 페이지일 때 last 의 값을 true 로 바꾸어 마지막 페이지 임을 알리도록 구현했습니다. 

### API
- fetcher 로 api 로직을 추상화 했습니다. 
  - get,post,delete,patch,put 별 method 분리
  - 각 상태 별 에러 처리

### Test
- 첫 페이지 불러오기, 무한스크롤 로 다음 페이지 잘 불러오는지 확인, 마지막 페이지 일 때 다음 페이지 불러오지 않는지 확인, 페이지 불러오는 중 로딩 상태인지 확인하는 테스트를 구현했습니다. 

## 리뷰 받고 싶은 부분
위에 적어둔 중요하게 생각한 부분과 에러 처리 위주로 리뷰 해주시면 감사하겠습니다! 그리고 이해하기 어려운 부분이 있다면 그 부분도 말씀해주시면 좋을 것 같아요!

추가 질문은 멘션으로 남기도록 하겠습니다!!

2024-06-01 05:28 UTC, uk960214 requested changes
안녕하세요 해시! 만나서 반갑습니다!
리뷰가 늦어서 죄송해요 ㅠㅠ
미션 구현하느라 고생 많으셨습니다!

👍 이런 점이 좋았아요!
- 스타일을 위한 테마, 타입 가드 등 사용 중인 기술을 잘 활용하는 법을 알고 계신 것 같아요!
- API 요청/응답 로직을 분리해주는 것도 좋았습니다!
- 전체적으로 코멘트를 많이 남길 것이 없이 깔끔했습니다!

🤔 이런 점은 조금 더 고민해볼까요?
- MSW를 활용해서 다양한 응답값을 보여주는 것은 좋은데, 요청과 조금 더 연결될 수 있도록 고도화해도 좋을 것 같아요!
- 혹시 배포된 페이지가 있을까요? 배포된 환경에서도 정상동작하는지 확인하고 싶습니다!

나머지 코멘트도 확인해서 다시 리뷰요청 주세요!

2024-06-01 05:28 UTC, uk960214 commented on src/api/product.ts
> +  const sortQuery = sortOptions ? `&sort=${encodedSort}` : '';
여기서는 모든 것들이 너무 문자열에 의존하고 있지 않나요?
page를 넘기고 싶지 않더라도 ?문자를 쓰기 위해서 필요하고, 추가적인 param을 넣어주려면 이 함수 자체를 넘겨주어야 하는 불편한 점이 있을 것 같아요!

2024-06-01 05:28 UTC, uk960214 commented on src/components/common/dropdown/Dropdown.tsx
> +        {isOpen &&
isOpen으로 조건부렌더링 하는 것이 dropdown되는 컴포넌트를 감싸주는 형식이 더 낫지 ㅇ낳나요??

2024-06-01 05:28 UTC, uk960214 commented on src/pages/productListPage/ProductListPage.tsx
> +  const { cartItems, handleAddCartItem, handleDeleteCartItem, matchCartItem } = useCartItems();
product와 cart의 정보를 최상위 페이지에서 호출하기로 결정하신 이유는 무엇일까요??

2024-06-01 05:28 UTC, uk960214 commented on src/mocks/handlers.ts
> +    const limit = page === 0 ? 20 : 4;
페이지 사이즈를 요청에서 온 것을 받지 않고 자체적으로 목 핸들러에서 처리하나요? 이 부분은 요청 받은 값을 토대로 처리해주면 좋지 않을까요??

2024-06-01 05:28 UTC, uk960214 commented on src/hooks/useProductList.ts
> +  }, []);
오프라인 -> 온라인이 되면 모든 오류 메시지를 초기화 하는걸까요? 이렇게 하기로 하신 이유가 무엇인가요?

2024-06-01 05:28 UTC, uk960214 commented on src/hooks/useDropdown.ts
> +const useDropdown = ({ resetPage }: UseDropdownProp) => {
useDropdown이라는 네이밍은 드롭다운 컴포넌트를 동작시키기 위한 기능을 담고 있는 훅으로 느껴지는데 실제로는 도메인 영역인 카테고리와 정렬을 설정하는 기능을 담고 있네요! 다른 이름이 더 적절하지 않을까요??

2024-06-03 15:59 UTC, dle234 reviewed
안녕하세요 블링 주말 잘 보내셨나요? 다양한 질문들과 꼼꼼한 피드백 감사해요!!
이번에 외부적인 요인이든 내부적인 요인이든 여러 이슈들이 많아서 제출 시간이 많이 늦어지게 되었다는 점 죄송합니다 🥹 

[➡ 배포](https://dle234.github.io/react-shopping-products/dist/)

### 수정 사항
- 에러 처리 테스트 추가
- 테스트 분리(페이지네이션 / 글 목록 불러오기)
- url 함수 분리, 네이밍 수정, 상수화 등 리팩토링
- handler 쿼리 참고

### 질문
useProductList 훅을 리팩터링 하고 싶은데 어떻게 하면 상태와 책임을 잘 분리할 수 있을지 고민이 되어서 하지 못했어요. 블링이라면 어떤 기준으로 분리할 것 같은지 궁금합니다!

2024-06-03 15:59 UTC, dle234 commented on src/pages/productListPage/ProductListPage.tsx
> +  const { cartItems, handleAddCartItem, handleDeleteCartItem, matchCartItem } = useCartItems();
product 와 cart를 사용하는 컴포넌트들이 여러개이며, 서로 자식-부모 관계가 아니라서 최상단에서 내려주게 되었습니다. 또한 모두 프롭스로 내려서 충분히 공유 가능하고, 프롭스를 내려주는 뎁스가 깊지 않아서 context Api 나 전역 상태관리 라이브러리를 사용하지 않았습니다

2024-06-04 11:05 UTC, uk960214 commented on src/__tests__/productList.test.ts
> +    });
좋습니다! 20, 4 같은 숫자들은 충분히 상수화해서 관리할 수 있을 것 같고 그러는 편이 관리하기 더 용이할 것 같아요!

2024-06-04 11:05 UTC, uk960214 commented on src/api/cart.ts
> +type MutationResponse = Record<'status', number>;
react-query와 이미 익숙하시군요! 차용해서 사용하는 것은 문제 없습니다.
다만 어떤 의미에서 mutation이라는 표현을 사용하는지를 생각해보고 가져오면 더 좋을것 같아요!

2024-06-04 11:11 UTC, uk960214 commented on src/hooks/useProductList.ts
> +  }, []);
음 당장 생각나는 방법을 대략 생각해보면
1. online이 되었을 때 자동으로 요청을 보내는 것은 아니지만, 온라인이 된걸 감지하면 버튼을 노출하고 클릭시 요청을 보내게 한다 (UX로 풀어보기)
2. 오류가 발생했을 때 retry하는 횟수를 제한해보기 (react query를 아신다면 기본 4번?)
3. 네트워크 오프라인 오류 상태와 나머지 오류 상태를 분리해서 관리하기
정도가 있을 것 같네요!

2024-06-04 11:19 UTC, uk960214 approved these changes
안녕하세요 해시! 피드백 반영하시느라 고생하셨습니다.
제가 봤을 때 useProductList 훅은 현재 따로 훅을 또 분리할만큼 복잡한거 같지는 않은데요!
그 내부 로직 자체를 어떻게 하면 깔끔하게 잘 리팩토링할까를 고민해보면 좋을 것 같습니다!

나머지는 크게 더이상 코멘트할 것은 남지 않아서, 이번 단계는 여기서 마무리하겠습니다.
남긴 코멘트들은 확인하고 2단계에서 반영할 내용이 있다면 반영해주세요!

그럼 2단계에서 뵙겠습니다!

2024-06-04 11:19 UTC, uk960214 commented on src/utils/createUrlQuery.ts
> +    ...(sortOptions ? [['sort', `price,${encodeURIComponent(sortOptions)}`]] : []),
왠지 어느정도 패턴이 반복되는 것 같은데, 이것도 더 단순화 해볼 법하다는 욕심이 나네요 ㅎㅎ

2024-06-04 11:19 UTC, merged