[1단계 - 상품 목록] 파란(안영훈) 미션 제출합니다.
woowacourse/react-shopping-products pull request #36
Opened 2024-05-30 08:52 UTC by greetings1012

다시 뵙네요, 지그! 이번 미션도 잘 부탁드립니다 😀

# 🚀 프로젝트 실행 방법

.env 파일을 파일 최상위에 저장
npm i
npm run dev

.env 파일은 슬랙 DM으로 드릴게요!

## 배포 링크

[vercel 배포 링크](https://react-shopping-products-10riw7ffr-greetings1012s-projects.vercel.app/)
사이트 들어간 후 주소창 왼쪽의 설정 버튼 -> 사이트 설정에서 안전하지 않은 콘텐츠를 허용해주시면 감사하겠습니다!

## 🧪 테스트 확인

npm run test

## 📕 스토리북 배포 링크

[스토리북 배포 링크](https://665837f3607efc34ca10a10b-swmxrqzfjf.chromatic.com/)

## 😭 놓친 부분

❌ msw를 이용한 useCartItem 커스텀 훅 테스트 중 post와 delete 테스트가 제대로 동작하지 않아요. 실제 서버와 통신했을 때에는 제대로 동작하는 것으로 보아 핸들러의 문제인 것 같지만 정확한 원인을 알아내지 못했어요.

❌ 오류가 발생할 경우 Toast가 제대로 등장하지만, 한번 등장한 후에는 setTimeOut으로 설정한 3000ms가 지나도 제대로 사라지지 않고 계속 갱신되면서 보여져요.

추가적으로 궁금한 내용은 각 코드에 달아놓을게요!
잘 부탁드립니다 👍

## 🌲 파일 구조

📦src
 ┣ 📂apis
 ┃ ┣ 📜carItems.ts
 ┃ ┣ 📜config.ts
 ┃ ┗ 📜products.ts
 ┣ 📂assets
 ┃ ┣ 📂images
 ┃ ┃ ┣ 📜AddToCartIcon.svg
 ┃ ┃ ┣ 📜MainLogo.svg
 ┃ ┃ ┣ 📜RemoveFromCartIcon.svg
 ┃ ┃ ┣ 📜ShoppingCartIcon.svg
 ┃ ┃ ┗ 📜chevronDown.svg
 ┃ ┗ 📜index.ts
 ┣ 📂components
 ┃ ┣ 📂DropdownContainer
 ┃ ┃ ┣ 📜DropdownContainer.style.ts
 ┃ ┃ ┗ 📜DropdownContainer.tsx
 ┃ ┣ 📂Header
 ┃ ┃ ┣ 📜Header.stories.tsx
 ┃ ┃ ┣ 📜Header.style.ts
 ┃ ┃ ┗ 📜Header.tsx
 ┃ ┣ 📂ProductItem
 ┃ ┃ ┣ 📜ProductItem.stories.tsx
 ┃ ┃ ┣ 📜ProductItem.style.ts
 ┃ ┃ ┗ 📜ProductItem.tsx
 ┃ ┣ 📂ProductItemList
 ┃ ┃ ┣ 📜ProductItemList.stories.tsx
 ┃ ┃ ┣ 📜ProductItemList.style.ts
 ┃ ┃ ┗ 📜ProductItemList.tsx
 ┃ ┣ 📂ProductItemSection
 ┃ ┃ ┣ 📜ProductItemSection.stories.tsx
 ┃ ┃ ┣ 📜ProductItemSection.style.ts
 ┃ ┃ ┗ 📜ProductItemSection.tsx
 ┃ ┣ 📂ProductItemTitle
 ┃ ┃ ┣ 📜ProductItemTitle.stories.tsx
 ┃ ┃ ┣ 📜ProductItemTitle.style.ts
 ┃ ┃ ┗ 📜ProductItemTitle.tsx
 ┃ ┣ 📂ToggleCartItemButton
 ┃ ┃ ┣ 📜ToggleCartItemButton.stories.ts
 ┃ ┃ ┣ 📜ToggleCartItemButton.style.ts
 ┃ ┃ ┗ 📜ToggleCartItemButton.tsx
 ┃ ┗ 📂common
 ┃ ┃ ┣ 📂Button
 ┃ ┃ ┃ ┣ 📜Button.stories.tsx
 ┃ ┃ ┃ ┣ 📜Button.style.ts
 ┃ ┃ ┃ ┗ 📜Button.tsx
 ┃ ┃ ┣ 📂Dropdown
 ┃ ┃ ┃ ┣ 📜Dropdown.stories.tsx
 ┃ ┃ ┃ ┣ 📜Dropdown.style.ts
 ┃ ┃ ┃ ┗ 📜Dropdown.tsx
 ┃ ┃ ┣ 📂PageTitle
 ┃ ┃ ┃ ┣ 📜PageTitle.stories.tsx
 ┃ ┃ ┃ ┣ 📜PageTitle.style.ts
 ┃ ┃ ┃ ┗ 📜PageTitle.tsx
 ┃ ┃ ┣ 📂Spinner
 ┃ ┃ ┃ ┣ 📜Spinner.stories.tsx
 ┃ ┃ ┃ ┣ 📜Spinner.style.ts
 ┃ ┃ ┃ ┗ 📜Spinner.tsx
 ┃ ┃ ┗ 📂Toast
 ┃ ┃ ┃ ┣ 📜Toast.stories.tsx
 ┃ ┃ ┃ ┣ 📜Toast.style.ts
 ┃ ┃ ┃ ┗ 📜Toast.tsx
 ┣ 📂constants
 ┃ ┗ 📜productList.ts
 ┣ 📂hooks
 ┃ ┣ 📜useCartItemList.test.ts
 ┃ ┣ 📜useCartItemList.ts
 ┃ ┣ 📜useIntersectionObserver.ts
 ┃ ┣ 📜useProductList.test.ts
 ┃ ┗ 📜useProductList.ts
 ┣ 📂interfaces
 ┃ ┣ 📜CartItem.ts
 ┃ ┣ 📜Product.ts
 ┃ ┗ 📜Sorting.ts
 ┣ 📂mocks
 ┃ ┣ 📂handlers
 ┃ ┃ ┣ 📂cartItemList
 ┃ ┃ ┃ ┣ 📜additionalProductData.json
 ┃ ┃ ┃ ┣ 📜cartItemListHandlers.ts
 ┃ ┃ ┃ ┗ 📜defaultData.json
 ┃ ┃ ┣ 📂productList
 ┃ ┃ ┃ ┣ 📜defaultData.json
 ┃ ┃ ┃ ┣ 📜expectedDefaultParamsData.json
 ┃ ┃ ┃ ┣ 📜expectedFitnessPriceDescData.json
 ┃ ┃ ┃ ┗ 📜productListHandlers.ts
 ┃ ┃ ┗ 📜index.ts
 ┃ ┗ 📜server.ts
 ┣ 📂pages
 ┃ ┣ 📜Product.stories.tsx
 ┃ ┣ 📜Product.style.ts
 ┃ ┗ 📜Product.tsx
 ┣ 📂store
 ┃ ┗ 📜QuantityContext.tsx
 ┣ 📂stories
 ┃ ┣ 📂assets
 ┃ ┃ ┣ 📜accessibility.png
 ┃ ┃ ┣ 📜accessibility.svg
 ┃ ┃ ┣ 📜addon-library.png
 ┃ ┃ ┣ 📜assets.png
 ┃ ┃ ┣ 📜avif-test-image.avif
 ┃ ┃ ┣ 📜context.png
 ┃ ┃ ┣ 📜discord.svg
 ┃ ┃ ┣ 📜docs.png
 ┃ ┃ ┣ 📜figma-plugin.png
 ┃ ┃ ┣ 📜github.svg
 ┃ ┃ ┣ 📜share.png
 ┃ ┃ ┣ 📜styling.png
 ┃ ┃ ┣ 📜testing.png
 ┃ ┃ ┣ 📜theming.png
 ┃ ┃ ┣ 📜tutorials.svg
 ┃ ┃ ┗ 📜youtube.svg
 ┃ ┣ 📜Button.stories.ts
 ┃ ┣ 📜Button.tsx
 ┃ ┣ 📜Configure.mdx
 ┃ ┣ 📜Header.stories.ts
 ┃ ┣ 📜Header.tsx
 ┃ ┣ 📜Page.stories.ts
 ┃ ┣ 📜Page.tsx
 ┃ ┣ 📜button.css
 ┃ ┣ 📜header.css
 ┃ ┗ 📜page.css
 ┣ 📂styles
 ┃ ┗ 📜Global.style.tsx
 ┣ 📂util
 ┃ ┗ 📜auth.ts
 ┣ 📜App.tsx
 ┣ 📜main.tsx
 ┗ 📜vite-env.d.ts

2024-05-30 09:04 UTC, greetings1012 commented on src/hooks/useCartItemList.ts
> +  };
한 훅에서 관리하는 값이 너무 많아 props drilling 문제가 일어났어요.
특히 isInCart의 경우 약 3번이나 값을 내려줘야 해 코드가 깔끔하지 않았던 것 같아요.
전역 상태를 사용하지 못하는 경우에는 이러한 방식이 최선인지 궁금합니다!

2024-05-30 09:04 UTC, greetings1012 commented on src/mocks/handlers/productList/productListHandlers.ts
> +export const productListHandlers = [
handler를 구현하면서 msw 테스팅의 의미에 대해 의문점이 생겼어요.
handler에서 서버 동작을 직접 구현해 test해야 하는데, 
이것보다는 fetch 데이터 대신 mock데이터를 직접 집어넣는 방식으로 테스트하는 것이 더 확실한 방법이지 않을까? 라는 생각이 들었어요.
지그의 msw 테스팅에 대한 생각이 궁금합니다!

2024-05-30 23:42 UTC, zigsong commented
@greetings1012 안녕하세요 파란~ 첨부해주신 배포 링크로 들어가면 다음과 같은 로그인 화면이 뜨는데요, 링크 다시 확인 부탁드립니다 

<img width="1720" alt="image" src="https://github.com/woowacourse/react-shopping-products/assets/44080404/5591d8d5-498a-46df-83e1-cf5102766619">

2024-05-31 00:29 UTC, zigsong requested changes
안녕하세요 파란~ 다시 만나 반가워요 👋 

msw를 활용한 이번 미션에서 여러가지를 공부하고 적용해보신 것 같네요! 

전반적으로 코드에 매우 신경써서 작업하셨다는 것이 느껴집니다. 

부분부분 개선이 필요한 곳들이 보여 코멘트 남겼어요. 질문에 대한 답도 코멘트에 남겨두었습니다! 

---

추가로, storybook 설치 시 딸려오는, 사용하지 않는 파일들(특히 asset)은 삭제해주세요 :)

2024-05-31 00:29 UTC, zigsong commented on src/hooks/useProductList.ts
> +          ]);
`page === 0`일 때도 똑같이

```jsx
setProductList((prevProductList) => [
            ...prevProductList,
            ...data.content,
          ]);
```

해도 똑같지 않나요? 🤔

2024-05-31 00:29 UTC, zigsong commented on src/components/ProductItemList/ProductItemList.tsx
> +    fetchNextPage();
IntersectionObserver에 observe 시 호출해야 하는 함수를 전달해서 호출하는 로직을 간결하게 잘 작성하셨네요 :D

2024-05-31 00:29 UTC, zigsong commented on src/apis/carItems.ts
> +import { generateBasicToken } from "../util/auth";
이 파일명에 오타가 있어용 `carItems`

2024-05-31 00:29 UTC, zigsong commented on src/apis/carItems.ts
> +    },
반복되는 header는 분리해볼 수 있을까요?

2024-05-31 00:29 UTC, zigsong commented on src/hooks/useCartItemList.ts
> +      setCartItemList(data.content);
에러가 발생했다면 다시 목록을 불러올 필요는 없을 것 같습니다.

추가/삭제 후 다시 목록을 불러오는 `requestFetchCartItemList`를 호출하고자 하는 의도였다면

`try~` 구문이 정상적으로 끝난 이후, 즉 `try~catch`구문 바깥에 작성해주는 게 좋을 것 같아요. 

`finally`에서는 `try`, `catch` 어떤 구문에 걸리든 상관없이 수행해야 하는 동작을 명시합니다. (ex. 로딩 상태 원복)

2024-05-31 00:29 UTC, zigsong commented on src/components/Header/Header.tsx
> +          {(quantity ?? 0) > 0 && (
이 조건문은 좀 이상한데요, 그냥

```jsx
quantity && ... 
```

로 작성해줘도 되지 않나요?? 

불필요한 연산자들이 많이 들어가있는 것 같습니다

2024-05-31 00:29 UTC, zigsong commented on src/components/common/Button/Button.stories.tsx
> +export const Playground: Story = {
스토리북까지 꼼꼼이 잘 챙겨주셨네요 👍

2024-05-31 00:29 UTC, zigsong commented on src/components/common/Button/Button.style.ts
> +export const Button = styled.button<ButtonProps>`
`Button` 컴포넌트를 자유롭게 사용할 수 있도록 섬세하게 잘 작성해주셨네요 😉

2024-05-31 00:29 UTC, zigsong commented on src/hooks/useCartItemList.test.ts
> +      );
에러 상태까지 테스트로 잘 작성해주셨네요 👋

2024-05-31 00:29 UTC, zigsong commented on src/mocks/handlers/cartItemList/cartItemListHandlers.ts
> +const mockCartItemList = cartItemListData;
이렇게 할당하면 객체를 복사하는 것도 아니고 그대로 할당하게 되는데, 

같은 객체를 참조하는 변수를 새로 만든 이유가 있으신가요?

2024-05-31 00:29 UTC, zigsong commented on src/mocks/handlers/cartItemList/cartItemListHandlers.ts
> +    }
여기서 post, delete 시에 `mockCartItem` 배열에 아이템을 추가, 삭제 한다고 해서 정말 defaultData.json에 있는 값이 바뀌게 될까요? 

msw를 활용한 테스트는 실제 DB를 가지고 테스트를 하는 것이 아니기 때문에, 운영 코드의 동작 방식과는 조금 다른 방식으로 테스트를 작성하는 수밖에 없습니다. `useCartItemList.test` 파일 안에서만 관리되는 `mockCartItemList`의 복사본을 만든 후, 테스트에서 post, deleete 동작 수행 후에 그 값이 어떻게 바뀌는지를 테스트하시면 될 거예요.

2024-05-31 00:29 UTC, zigsong commented on src/mocks/handlers/productList/productListHandlers.ts
> +export const productListHandlers = [
오... 네 맞습니다.
 
지금 우리는 '서버 코드'를 테스트하려는 게 아니라, '서버에서 내려오는 응답값으로 프론트 로직이 잘 그려지는지'를 테스트해야 해요. 

그러므로 지금처럼 서버의 모든 로직을 msw handler 안에 넣을 필요는 없습니다. 

확인하고자 하는 API 호출의 응답값만 임의로 넣어서 적절한 상태코드와 함께 반환하는 식으로 handler를 작성해주시면 됩니다 :) 

이 코드는 수정이 필요하겠네용.

2024-05-31 00:32 UTC, zigsong commented on src/hooks/useCartItemList.ts
> +  };
흠 제가 생각했을 때는 `isInCart` 값의 prop drilling이 그렇게 심하지 않다고 생각합니다. 필요한 컴포넌트들에 잘 들어갔구요. 

만약 이것이 조금 아쉬우시다면 전역 상태를 사용해도 될 것 같은데요, 왜 전역 상태를 사용하지 못하나요? 

필요하다면 `cartItemList` 목록을 전역 상태에 담아도 될 것 같습니다.

2024-05-31 08:57 UTC, greetings1012 commented on src/apis/carItems.ts
> +import { generateBasicToken } from "../util/auth";
수정했습니다! 👍

2024-05-31 17:20 UTC, greetings1012 commented on src/hooks/useCartItemList.ts
> +  };
생각해보니 useContext를 통해 전역 상태로 관리할 수도 있겠군요! 
App 최상단에서는 quantity에는 사용했는데 왜 잊었을까요...
다만 지그의 리뷰를 보고 곰곰이 생각해보니,
quantity와 getQuantity를 각자 다른 곳에 내려줘야 했던 것과 다르게 isInCart의 경우에는 하나의 값을 바로 boolean으로 바꿔 내려주는 상태이므로 굳이 전역 상태로 관리할 필요까지는 없다고 판단하게 되었습니다!
이 코드는 이대로 유지하도록 하겠습니다 😁

2024-05-31 17:28 UTC, greetings1012 commented on src/mocks/handlers/cartItemList/cartItemListHandlers.ts
> +const mockCartItemList = cartItemListData;
msw 공식 문서를 보고 제가 잘못 생각한 부분이 있었어요.
핸들러 바깥에 const를 선언하면 그것이 handler 전체에서 유지되는 가상 임시 데이터베이스처럼 사용되어
handler를 사용하는 중에는 값이 항상 저장되고 유지되는 형태인 줄로 오해했습니다 🥲

cartItemListData를 바로 사용하도록 수정했습니다!

2024-05-31 17:54 UTC, greetings1012 commented on src/mocks/handlers/cartItemList/cartItemListHandlers.ts
> +    }
바로 위 리뷰에서 말씀드렸던 대로, handler를 사용하는 데 있어서 제가 큰 오해를 하고 있었어요 😭

테스트 부분에서는 실제 서버 통신과는 다르게 handler가 결과 배열을 반환하게 한 후, 그 값을 비교하는 방식으로 리팩터링해 테스트 통과에 성공했습니다!
mockCartList는 원래 데이터에 additionalData를 추가하는 식으로 테스트 함수에서 구현했어요!
지그가 말씀하신 방법이 이 방법이 맞을까요?
(주석 해제되고 수정된 테스트 코드와 핸들러를 확인해주시면 감사하겠습니다 🙇‍♂️)

2024-05-31 18:58 UTC, greetings1012 commented on src/apis/carItems.ts
> +    },
공통 로직을 분리해 하나의 함수로 만들었어요!

2024-05-31 19:00 UTC, greetings1012 commented on src/components/Header/Header.tsx
> +          {(quantity ?? 0) > 0 && (
급하게 로직을 수정하는 과정에서 놓친 듯 하네요 😭

수정했습니다!

2024-06-01 17:18 UTC, greetings1012 commented on src/hooks/useCartItemList.ts
> +      setCartItemList(data.content);
혹시 낙관적 업데이트를 수행하기 위해 먼저 quantity를 수정하고,
try-catch문에서 cart 내용이 업데이트 되거나 에러를 반환한 후
실패하던 성공하던 requestFetchCartITemList로 낙관적 업데이트한 값을 서버와 다시 동기화시킨다는 개념에서
위 메서드를 finally에 넣는 관점은 어떻게 생각하시나요?
지그의 의견이 궁금해요! 🧐

2024-06-01 18:18 UTC, greetings1012 commented on src/interfaces/Sorting.ts
> +  "price%2Cdesc" = "가격 높은 순",
%2C 대신 쉼표만 url로 전달해도 자동으로 변환해서 인식하는군요!
수정했습니다

2024-06-01 19:20 UTC, greetings1012 commented on src/components/ProductItemSection/ProductItemSection.tsx
> +    "price,asc" as Sorting
수정했습니다!
지그의 코멘트를 보고 고민했는데, ProductItemSection.ts에서 핸들러를 구현할 때, 아래와 같이 타입 단언을 하는 부분도 있었어요.
```
const handleCategoryChange = (e: React.ChangeEvent<HTMLSelectElement>) =>
  setCategory(e.target.value as Category);
const handleSortingChange = (e: React.ChangeEvent<HTMLSelectElement>) =>
  setSortingOption(e.target.value as Sorting);
```
이벤트리스너가 이벤트 내용을 string으로 받아와 어쩔 수 없이 단언을 해 준 부분이었는데, 이 부분도 바꾸는 것이 좋을까요?
저는 enum을 Object 배열로 매핑해 드롭다운으로 넘겨준 시점에서 모든 value는 Sorting(혹은 Category) 값임을 보장할 수 있어 타입 단언을 사용해도 괜찮다고 생각해요.
지그의 생각이 궁금합니다! 😄

2024-06-01 19:23 UTC, greetings1012 commented on src/components/ProductItemSection/ProductItemSection.tsx
> +  const [category, setCategory] = useState<Category>("" as Category);
처음에는 각 상품에 카테고리에 '전체'(혹은 "all") 라는 값이 없어 Category에 전체를 넣는 것을 보류했었는데,
지금 보니 Category는 드롭다운 등 실제 데이터보다 클라이언트에서의 타입 관리에 중점을 두는 enum이라
전체 = "" 값을 추가하는 것이 구현하는데 있어 편리하겠다는 생각이 드네요!
수정했습니다 😆

2024-06-01 19:23 UTC, greetings1012 commented on src/components/common/Dropdown/Dropdown.tsx
> +            );
위의 수정 내용들을 반영하면서 같이 수정해 주었습니다!
확실히 배열로 관리하니 리팩터링 때도 한참을 헤매게 되네요 😅

2024-06-01 19:59 UTC, greetings1012 commented on src/App.tsx
> +  };
이틀 동안이나 계속 보았지만, 결국 정확한 이유를 파악하지는 못했어요 ☹️
다만 예상해보건대, props drilling이 일어나는 과정에서 렌더링이 계속 트리거되어 handleError가 계속 실행되는 것 같아요.
그에 따라 setMessage 혹은 setShowToast가 계속 실행되며 state가 바뀌고, 그것이 다시 app을 리렌더링하게 만들어 Toast가 사라지지 않는 것 같다고 생각했어요.
일단은 ProductList에서만 에러가 발생하므로 ProductList에서 직접 Toast를 호출하도록 수정했습니다 😢

2024-06-03 04:26 UTC, greetings1012 commented on src/mocks/handlers/productList/productListHandlers.ts
> +export const productListHandlers = [
테스트 코드를 수정하는 중,

> 만약 핸들러를 이용해 테스트 코드 동작뿐만이 아니라 브라우저단까지 모킹을 하는 경우에는 
> 모든 경우의 수에 대응하기 위해 서버의 기능까지 handler에서 구현해야 하겠는데?

라는 생각이 들었어요.
서비스의 규모가 커지게 되면
각 카테고리와 그에 따른 정렬 데이터까지 따로따로 조건문으로 값을 반환하는 것보다는
서버 로직을 직접 구현하는 것이 더 간편할 수도 있겠다라는 생각이었어요.
(한 번 구현이 끝나면 다시 수정할 필요가 없으므로)

지그의 생각은 어떠신지 궁금합니다! 🧐

2024-06-03 11:34 UTC, zigsong commented on src/mocks/handlers/productList/productListHandlers.ts
> +export const productListHandlers = [
> (한 번 구현이 끝나면 다시 수정할 필요가 없으므로)

라는 말이 틀렸기 때문에 제 의견은 반대입니다... 😵 

서버 구현도 완벽하지 않고, 버그를 계속 수정하거나 엣지 케이스들이 늘어날 수도 있어요. 

프론트 msw에서 계속 f/u하며 구현하는게 잘못된 것은 아니겠지만... 굳이 아쉬운 시간을 그렇게 사용할 필요는 없을 것 같아요 🙃

2024-06-03 11:35 UTC, zigsong commented on src/components/ProductItemSection/ProductItemSection.tsx
> +    "price,asc" as Sorting
파란이 코멘트 남겨주신 부분은 괜찮습니다 :) option의 value는 항상 `string`으로 넘어오기 때문에 어쩔 수 없는 부분이기도 해요

2024-06-03 11:37 UTC, zigsong commented on src/hooks/useProductList.ts
> +          ]);
아이공. 섬세하게 구현해주셨군요. 설명 감사합니다!

2024-06-03 11:44 UTC, zigsong commented on src/hooks/useCartItemList.ts
> +  };
불필요한 중괄호와 `return`을 줄이고 다음과 같이 써줄 수 있습니다 :) 

```jsx
const target = cartItemList.find((item) => item.product.id === product.id);
```

2024-06-03 11:44 UTC, zigsong commented on src/hooks/useCartItemList.ts
> +      setCartItemList(data.content);
1. 낙관적 업데이트를 수행하기 위해 먼저 quantity를 변경하는 것은 좋습니다. 
2-a. try문에서 cart 내용이 업데이트되는 경우 -> try-catch문 바깥에서 서버와 동기화를 수행합니다. 
2-b. catch문에서 에러가 발생한 경우 -> 서버와 동기화를 수행할 필요가 없으며, 사용자향 에러메시지와 함께 먼저 변경한 quantity를 다시 원복합니다. 
3. finally에서는 추가 API 콜을 하지 않는 것이 좋습니다. finally의 추가 API 콜이 에러를 던지는 경우에는 어떻게 해야 하나요?

2024-06-03 11:44 UTC, zigsong commented on src/mocks/handlers/cartItemList/cartItemListHandlers.ts
> +const mockCartItemList = cartItemListData;
아하 그렇게 오해할 만 하네요 🥲

2024-06-03 11:57 UTC, zigsong approved these changes
안녕하세요 파란~ 짧은 시간 동안 미션 요구사항과 리뷰 모두 잘 반영해주셔서 감사합니다 😉 

msw가 사실 좋아보이지만 사용이 결코 쉬운 친구가 아닌데 이번 기회를 통해 잘 배워가셨으면 좋겠습니다! 

질문 주신 내용들에 대해 추가 코멘트 남겼는데요, 2단계를 진행하면서 마저 같이 고민해봐도 좋을 것 같습니다! 

또 만나요 👋

2024-06-03 11:57 UTC, zigsong commented on src/hooks/useCartItemList.test.ts
> +    1;
덩그러니 놓여있는 `1`...

2024-06-03 11:57 UTC, zigsong commented on src/mocks/handlers/cartItemList/cartItemListHandlers.ts
> +    }
넵! 커밋이 많아 이전 주석의 상태가 어떤 상태였는지 정확히 찾진 못했지만, 지금처럼 작성해주시면 됩니다 :)  👋

2024-06-03 11:57 UTC, zigsong commented on .eslintrc.cjs
> +          },
요런 `pattern`들은 다른 곳에서 가져오고 삭제를 안한 것 같네요~

2024-06-03 11:57 UTC, zigsong commented on src/hooks/useProductList.test.ts
> +      );
로딩 상태까지 꼼꼼하게 테스트를 작성해주셨네요 😉

2024-06-03 11:57 UTC, merged

2024-06-04 07:14 UTC, greetings1012 commented on src/mocks/handlers/productList/productListHandlers.ts
> +export const productListHandlers = [
테스트와 mockdata를 단순화시켜 좀 더 유연한 상황에 대응할 수 있도록 했습니다!
백엔드 api가 구현이 끝난 후 다시 수정될 경우에 대해 생각하지 못했네요