[1단계 - 상품 목록] 토다리(이태훈) 미션 제출합니다.
woowacourse/react-shopping-products pull request #39
Opened 2024-05-30 08:58 UTC by Todari

안녕하세요 블링!
이번에 상품목록 미션 리뷰를 부탁드릴 토다리입니다 :)
MSW와 비동기 에러 테스트 및 에러 처리에 많은 시간을 쏟다보니 완성도가 높지 않네요... 😭 
잘부탁드립니다!

---
# How to test
## Links

### [storybook](https://6658366cc292113328b8716c-pateujzkud.chromatic.com/)
### [product app](https://react-shopping-products-f1levo8nh-todaris-projects.vercel.app/)

product app의 경우 브라우저 설정에서 _안전하지 않은 콘텐츠 - 허용_ 옵션을 설정해줘야 합니다!

## Terminal
```
npm run dev // app
npm run storybook // storybook
```
를 이용하여 터미널에서 실행할 수 있습니다.

# Motivation
- MSW를 이용하여 API mocking test 를 진행하고, 유용함과 필요성을 느껴보기 위해 노력했습니다.
- 효율적인 component 분리를 위해 노력했습니다..
- 다양한 pending 및 error 상태에 대응할 수 있도록 했습니다.
- storybook을 통해 핵심 component UI들을 한눈에 파악할 수 있게 했습니다.

# 아쉬운 점
- 시간이 많이 부족해, component/hook 등 역할에 따른 코드 분리를 제대로 하지 못한 부분이 아쉽습니다.
- 평소에 비해 storybook 및 component에 대한 분리가 부족한 것 같아 아쉽습니다.
- API를 모킹하는 MSW가 아닌 다른 부분에 대해서 테스트 코드를 많이 작성하지 못한 부분이 아쉽습니다.
- 구현 및 테스트코드에 너무나도 많은 시감을 소비하여 평소 UX에 신경을 쓰는 것 만큼 세세한 유저 행동 패턴 및 플로우를 고려하지 못한 것이 아쉽습니다.
- useCartItemList hook에서 테스트를 통과시키지 못한 부분이 있어 주석처리를 해두었습니다.

# To Reviewers
## useProductList의 prop drilling
`dropdown`과 `productList`에서 `useProductList`의 반환값들을 공통으로 사용하기 위해 두 컴포넌트의 공통 부모에서 prop을 내려주고 있습니다. 이정도면, 적은 단계의 prop drilling이며 복잡한 단계가 아니라라고 생각해서 prop을 내려주어 진행하였습니다.

하지만, header 부분에서 장바구니 아이템의 갯수를 나타내는 것을 위해서는, 너무 많은 단계로 넘겨줘야 하기 때문에, `QuantityContext`를 이용하여 전역으로 관리를 해 주었습니다.

지난 단계에서 전역 상태를 사용했던 것이 나름 편했는지, 이 부분에 대해서 전역상태와 prop에 대해서 고민을 하게 되었던 것 같습니다.

이런 상태 설계에 대해서 어떻게 생각하시는지 궁금합니다.

## 비동기 fetching과 클라이언트 상태에 대한 로직
현재 코드에서 설계된 전체적인 비동기 fetching, 그리고 client 상태 관리에 대해서 어떻게 생각하시는지 간단한 의견을 듣고 싶습니다!

---

잘부탁드립니다 🚀🚀🚀🚀🚀

2024-06-01 04:21 UTC, uk960214 requested changes
안녕하세요 토다리! 리뷰가 늦어져서 죄송합니다 ㅜㅜ
구현하느라 고생 많으셨습니다!

👍 이런 점이 좋았어요
- 장바구니 버튼을 클릭했을 때 전화효과를 주는 것처럼 UX에 신경을 쓴 부분들이 눈에 들어왔습니다! 사소하지만 결과물의 퀄리티가 많이 올라간 것 같아요
- 전반적으로 구성이 잘 되었다고 느꼈고 컴포넌트와 훅 분리도 이 정도라면 잘 이루어졌다고 생각했습니다!

🤔 이런 점은 조금 더 생각해볼까요?
- 코멘트를 참고해서 코드 전체적으로 리팩토링을 해주면 좋을 것 같아요!
- 지금 분리된 커스텀 훅 일부에는 API 로직과 나머지 컴포넌트/페이지에 필요한 로직이 섞여있는데, API 스펙이 바뀔 때와 UI 디자인이 바뀔 때에 서로 간의 영향도를 최소한으로 하려면 분리해주어도 좋지 않을까요?
- 테스트 파일이 매우 긴데요, 이걸 분리하는 편이 관리가 더 쉽지 않을까요?
- 공통 기능 (toast, errorHandler 등)을 어떻게 구성하고 관리할 지에 대해서도 조금 더 고민해보아도 좋을 것 같아요!

프롭 드릴링은 문제 없을 것이라고 생각했습니다!

나머지 코멘트도 확인해서 다시 리뷰요청 주세요!

2024-06-01 04:21 UTC, uk960214 commented on src/hooks/useProductList.test.ts
> +      });
productList의 length가 20이라는 것이 이 테스트에 대한 확실한 통과조건이 될 수 있을까요?
상품 목록의 기본 요청 길이가 20이 아니라면 어떻게 되나요? 혹은 목데이터의 길이가 줄어서 20개를 요청했지만 15개만 오면 어떻게 되나요?

2024-06-01 04:21 UTC, uk960214 commented on src/mocks/handlers/productList/productListHandlers.ts
> +          PRODUCT_LIST.initialPageProductQuantity;
변수명이 길고 수식이 짧지 않아서 로직을 파악하기 쉽지 않네요!
조금 더 가독성을 높일 수 있는 방법은 없을까요?

2024-06-01 23:40 UTC, Todari commented on src/components/common/Button/Button.stories.tsx
> +const meta = {
각 args의 description이 의미없는 문자열들이었네요...!
제거해주었습니다!
추후 시간이 남으면 storybook docs의 description도 의미있는 값으로
채워볼 수 있도록 하겠습니다 :)

88f7733

2024-06-01 23:41 UTC, Todari commented on src/hooks/useCartItemList.test.tsx
> +  // describe("장바구니 추가 및 제거", () => {
테스트 통과가 생각대로 이루어지지 않아서 우선 주석처리해놓고 방법을 생각하고 있었습니다 ㅜㅜ
리팩토링을 마무리 하는 과정에서 문제를 파악하고 해결해 볼 수 있도록 하겠습니다~!

2024-06-02 01:14 UTC, Todari commented on src/App.tsx
> +        createPortal(<Toast message={toastMessage} />, document.body)}
블링이 얘기해 주신 대로, `Toast`안으로 넣어주는 것이 좋을 것 같습니다.
showToast, createPortal 모두 Toast component가 렌더링 되는 방식에 대한 것이다 보니, 외부에 알려지는 것 보단, Toast component 내부에 작성되는게 더 나을 것 같네요!

f0b9a3e

2024-06-02 05:06 UTC, Todari commented on src/apis/carItems.ts
> +  return data;
b75e54c

말씀해 주신 대로 작업한다면, 더 보기 좋게 될 것 같습니다 :)
 
```tsx
const response = async ({ url, method, body, errorMessage }: ResponseProps) => {
  const response = await fetch(url, {
    method: method,
    headers: {
      "Content-Type": "application/json",
      Authorization: token,
    },
    body: body,
  });

  if (!response.ok) {
    throw new Error(errorMessage);
  }

  if (method === "GET") {
    const data = await response.json();
    return data;
  }
};
```

한가지 궁금한 점이, GET인 경우에만 값을  return하기 때문에, method에 따라서 반환이 있을수도, 없을수도 있어서 이렇게 처리를 했는데 이부분에 대해서 어떻게 생각하시는지 궁금합니다!

2024-06-02 05:07 UTC, Todari commented on src/apis/carItems.ts
> +    throw new Error("Failed to fetch cart item list");
동의합니다! 실습때 예시코드를 참고하여 하다 보니, 에러메세지를 그대로 영어로 작성했네요 😓 

위 comment 반영하면서 함께 처리했습니다!

2024-06-02 05:38 UTC, Todari commented on src/components/DropdownContainer/DropdownContainer.tsx
> +  );
말씀하신 부분에 동의합니다! spread연산자를 이용해서 한번에 선언해 줄 수 있겠네요! 뿐만 아니라, 현재 코드가 사용되는 곳마다 통일성이 없이 enum의 키, enum의 값, type  등 무분별하게 사용되고 있어서, enum이 아닌, 객체를 이용해서 전반적으로 혼란 없이 category, sort 를 관리할 수 있도록 변경해 주었습니다!

8b7f0fc

2024-06-02 06:22 UTC, Todari commented on src/components/ProductItem/ProductItem.style.ts
> +`
예상치 못한 동작을 방지하기 위해서 예전부터 파일의 끝에 개행문자를 추가해 왔어서 이를 지키지 않으면 EOL경고를 띄워주는 것으로 알고있습니다!

lint를 의도대로 작동시키지 않아서 이런 상황이 발생했네요 ㅜㅜ

수정해 주었습니다!

2024-06-02 06:22 UTC, Todari commented on src/components/common/Button/Button.style.ts
> +  }
감사합니다 👍👍👍

2024-06-02 06:31 UTC, Todari commented on src/components/common/Button/Button.style.ts
> +  }}
f4fd7bd

말씀해 주신대로 변경하니 확실히 한결 보기 편하네요!
감사합니다 :)

2024-06-02 06:35 UTC, Todari commented on src/components/ToggleCartItemButton/ToggleCartItemButton.tsx
> +      }}
동일하지 않습니다!
제가 작성한`onClick={()=>{onClick()}}`과 같은 경우엔, 렌더링이 진행될 때 마다 새로운 함수를 생성해서, 성능의 미묘한 차이를 줄 수 있을 것 같습니다.
prop으로 받은 onClick을 이용해 추가 로직을 만들어 주는 것이라면 제가 작성한 것 처럼 작성해야 좋겠지만, 여러가지 상황을 파악해 봤을 때, 블링이 제안해 주신 `onClick={onClick}`을 사용하는 것이 좋아보입니다 :)

반영하도록 하겠습니다~!

61d485b

2024-06-02 06:35 UTC, Todari commented on src/interfaces/Sorting.ts
> +}
페어와 작업할 때 이부분에 대해서 논의하다가, key value를 모두 활용해서 dropdown을 이용하고자 enum을 사용했었습니다.
하지만 위에서 category, sort 관련 리팩토링을 진행할 때,
이부분을 object로 관리하는 것이 더 좋을 것 같아서 object로 변경되었습니다!

2024-06-02 07:15 UTC, Todari commented on src/components/Header/Header.tsx
> +          ></S.ShoppingCartIconContainer>
블링이 말씀하신 대로, img태그를 그대로 사용해도 괜찮을 것 같습니다!
하지만, SVG이니만큼, SVGcomponent로써 사용하는 방법으로 변경해보았습니다:)

a8ca49e

2024-06-02 08:50 UTC, Todari commented on src/App.tsx
> +  };
86a4745

얘기하신것을 생각해보니, 확실히 어색한 부분이 있는 것 같습니다!
지난 미션 같은 경우엔, Errorboundary로 처리해 줬는데, 이번 미션의 요구사항은
대체 fallback을 보여주는것이 아닌, 일시적인 toast를 띄워주는 것이라 어떻게 처리해야하나 고민이 있었습니다.

전역으로 error를 발생시켜서, toast  내부에서 처리하는 방법으로 변경했습니다~!

2024-06-02 08:59 UTC, Todari commented on src/components/ProductItemList/ProductItemList.tsx
> +  });
위의 onClick에서 말씀해 주신 것과 비슷한 맥락이네요!
반영하겠습니다 :)

ea407e4

2024-06-02 09:12 UTC, Todari commented on src/mocks/handlers/productList/productListHandlers.ts
> +          PRODUCT_LIST.initialPageProductQuantity;
85b10ef

변수 자체를 조금 짧게 수정하고, 수식에서 사용되는 일부 부분을 별도의 상수화를 진행해서 의미를 조금 더 알기 쉽고, 가독성이 있도록 변경하였습니다!

2024-06-02 10:46 UTC, Todari commented on src/hooks/useProductList.test.ts
> +      });
우선, comment와 별개로 테스트가 종종 다른 결과를 반환하길래 확인해 본 결과
`price,asc` 정렬 옵션으로 api를 요청했을 때, 같은 가격의 아이템들에 대한 두번째 정렬 우선순위가 무작위로 반환되더라구요!
이에 대해서 일관된 data를 위해 두번째 인자에 name,asc 정렬 옵션을 추가해 주었습니다.
2b7bcb1

또한, 말씀하신 대로 다양한 case에 대응하지 못하고 있는 것 같아서, 이에 맞게 해결해주었습니다 :)
3a4bf13

2024-06-03 12:22 UTC, uk960214 approved these changes
리뷰 반영하느라 수고 많으셨습니다 토다리!
피드백이 아주 잘 반영된 것 같아요! 아주 깔끔하네요!!
몇가지 질문과 피드백을 더 드렸는데요 큰 틀에서는 수정할 부분이 없을 것 같아서,
나머지 부분들과 개선은 2단계를 진행하면서 마저 수정해주세요!

그럼 2단계에서 뵙겠습니다!

2024-06-03 12:22 UTC, uk960214 commented on src/hooks/useProductList.ts
> +    console.log(page, category, sort);
이 console.log는 지워도 되는 것이겠죠?

2024-06-03 12:22 UTC, uk960214 commented on src/components/common/Toast/Toast.tsx
> +    }
오류를 보여주고 난 뒤에는 error는 초기화해주지 않아도 괜찮은가요?

2024-06-03 12:22 UTC, merged

2024-06-04 05:11 UTC, Todari commented on src/apis/products.ts
> +  const sortOptionQuery = `sort=${sortOption}&sort=name,asc`;
url searchParams 메소드들을 활용해 보는 방법들이 있을 것 같아요!
step2에서 적용시켜 볼 수 있도록 하겠습니다 :)

2024-06-04 05:12 UTC, Todari commented on src/components/common/Dropdown/Dropdown.tsx
> +            </S.Option>
오... 생각하지 못한 좋은 방법이 있었네요!
객체에서의 구조분해는 자주 해서 익숙한데, 배열은 아직 익숙하지 않은 것 같아요 :)

감사합니다!!

2024-06-04 05:12 UTC, Todari commented on src/hooks/useProductList.ts
> +    console.log(page, category, sort);
맞습니다 ㅜ 마지막에 지우는걸 깜빡했네요

2024-06-04 05:13 UTC, Todari commented on src/store/QuantityContext.tsx
> +export const QuantityContext = createContext<QuantityContextType | null>(null);
장바구니 전체 정보는 context 로 관리하지 않고 있습니다.
productList 를 불러오는 곳에서, 이미 담긴 product인지 판단하기 위해 가져왔었는데,
장바구니의 갯수만을 header에서 사용해야 하는데, prop 전달이 너무 어려울 것이라고 판단해서 갯수는 전역 상태로 관리하기로 결정했습니다!

2024-06-04 05:14 UTC, Todari commented on src/components/common/Toast/Toast.tsx
> +    }
UI적으로는, toast가 이미 사라지기 때문에 큰 차이가 없을 것이라고 생각하지만,
추후 다른 기능들이 들어오거나, 다른 error 관련 로직이 생길 때, 이부분이 발목을 잡을 수 있다고 판단해서 저도 초기화 해주는 것이 맞다고 생각합니다!
step2에서 반영해보겠습니다