[1단계 - 상품 목록] 텐텐(최진실) 미션 제출합니다.
woowacourse/react-shopping-products pull request #4
Opened 2024-05-30 07:51 UTC by chlwlstlf

2024-05-30 08:53 UTC, chlwlstlf commented on src/mocks/cartItem/cartItem.ts
> +  }),
아이템 빼기 테스트를 실패하였습니다. delete 요청이 아예 가지 않는 것 같았습니다. 코드 상에 문제가 있는 것인지 서버의 오류인지 원인을 찾아내지 못 하여 질문드립니다! get과 post의 요청은 잘 작동합니다😂

2024-05-30 08:53 UTC, chlwlstlf commented on src/hooks/useCartItems/useCartItems.ts
> +  };
## fetch를 두 번 하는 이유

- 장바구니 목록도 size가 default로 20인 페이징으로 구현되어있습니다.
- 따라서 장바구니 아이템 개수가 20개가 넘어가면 0 페이지 이후의 아이템들을 불러오지 못 하였습니다.
- 이를 해결하기 위해 첫 번째 fetch로 totalElements를 얻습니다.
- 이것이 20보다 작다면 바로 데이터를 반환합니다.
- 20보다 크다면 totalElements 값을 size에 넣어주어 한 페이지로 모든 값을 가져올 수 있게 하였습니다.

2024-05-30 08:53 UTC, chlwlstlf commented on src/hooks/useProducts/useProducts.ts
> +  };
- page가 0일 때는 데이터를 그대로 반환하고, 그 이후부터는 원래 데이터에 4개가 추가된 데이터를 반환합니다.
- api 반환값의 `last` 를 저장합니다. 무한 스크롤의 `관찰 대상` 을 last가 false일 때만 띄우기 위해 사용합니다.

2024-05-31 00:58 UTC, zigsong requested changes
안녕하세요 텐텐~ 다시 만나 반갑습니다 😉 

레벨2 마무리를 앞두고 그동안 정말 많이 단련하신 건지 바로 실무에 투입해도 될 만큼 훌륭하게 미션을 잘 구현해주셨네요. 

코멘트 남길 부분들이 많지 않지만 아쉬우실 것 같아서 여기저기 핀잔을(ㅋㅋ) 늘어놔봤습니다. 

--- 

> 2단계 때 react-query를 사용한다는 소식을 듣고 context api를 사용하는 팀들이 많았습니다. 아직 props drilling을 크게 겪지 못 했고, 결국 prop으로 fetch 데이터를 내려주었습니다. 2단계를 대비하여 context api로 바꾸는 것이 좋을지 아니면 바로 react-query를 적용하는 것이 좋을지 고민이 됩니다. 피드백 할 때 context api를 사용하는 방향으로 바꾸는 것이 좋을지 지그의 의견이 궁금합니다..!😊

-> 필요할 것 같은 상태를 전역으로 미리 분리해두는 것도 잘못된 건 아니지만, 텐텐처럼 우선은 그냥 prop drilling을 사용하고 그 정도가 나쁘지 않다면 그대로 두는 것이 더 좋다고 생각합니다. 2단계로 넘어가면서도 react-query 등 서버 상태를 관리할 수 있는 도구를 사용한다면 context api가 굳이 필요없을 수도 있어요. 저는 텐텐의 지금 작성 방식에 동의합니다

2024-05-31 00:58 UTC, zigsong commented on src/components/Header/Header.style.tsx
> +`;
무엇 때문인지 header가 가로로 꽉 차지 않는 문제가 있는데요, 

모든 모바일 화면에서 header가 다 채워지도록 스타일을 수정해주세요! 

<img width="423" alt="스크린샷 2024-05-31 오전 9 33 46" src="https://github.com/woowacourse/react-shopping-products/assets/44080404/8ddb30d0-d6f4-49e8-bd54-3128add8be51">

2024-05-31 00:58 UTC, zigsong commented on src/pages/ProductListPage/ProductListPage.tsx
> +  );
카테고리 필터를 변경하여 `handleCategory` 옵션 변경 시 보이는 것처럼 ProductList의 상위 2개의 항목은 바뀌지 않고 그 다음 항목들부터 바뀌고 있는데요, 어떤 버그일까요? 👀 



https://github.com/woowacourse/react-shopping-products/assets/44080404/cf0e3c83-f838-48aa-a2b2-2bb0392e9dcf

2024-05-31 00:58 UTC, zigsong commented on src/constants/optionList.ts
> +];
dropdown에 필요한 값과 라벨을 객체로 잘 관리해주셨네요 😉

2024-05-31 00:58 UTC, zigsong commented on src/hooks/useProducts/useProducts.ts
> +  };
`useProducts`에서 수행하는 로직도, 반환하는 값도 너무 많아 헷갈리는데요, sorting과 category 등을 먼저 분리하여 관심사를 분리해볼 수 있을까요?

2024-05-31 00:58 UTC, zigsong commented on src/hooks/usePagination.ts
> +const usePagination = (): UsePaginationResult => {
무한스크롤 로직을 별도의 hook으로 분리하여 잘 작성해주셨습니다 👋 

실제로 사용해도 될 코드 같네요

2024-05-31 00:58 UTC, zigsong commented on src/hooks/useProducts/useProducts.ts
> +    setProducts(page === 0 ? data : [...products, ...data]);
`page === 0`일 때에도 그냥 `[...products, ...data]` 해줘도 똑같지 않나요?

2024-05-31 00:58 UTC, zigsong commented on src/pages/ProductListPage/ProductListPage.tsx
> +          <S.CartNumber>{cartItems.length <= SIZE.DEFAULT ? cartItems.length : `${SIZE.DEFAULT}+`}</S.CartNumber>
오 20개가 넘어가면 `20+`로 표시되게 했군요. 신선하고 좋은 아이디어 같습니다 :D

2024-05-31 00:58 UTC, zigsong commented on src/hooks/useCartItems/useCartItems.ts
> +    const { data: initialData, totalElements } = await fetchCartItems(20);
여기도 매직넘버 `20` 대신 `SIZE.DEFAULT`를 사용해주면 좋을 것 같아요~

2024-05-31 00:58 UTC, zigsong commented on src/api/apiClient.ts
> +};
반환하는 응답과 에러 핸들링 로직의 일관성을 유지하며 추상화해서 멋진 코드가 되었네요! 

이것도 조금만 다듬어서 실무에 갖다 써도 될 것 같습니다 ㅎㅎ

2024-05-31 00:58 UTC, zigsong commented on src/api/apiClient.ts
> +  }
오프라인 확인까지 섬세하게 챙겨주셨네요 ㅎㅎ

2024-05-31 00:58 UTC, zigsong commented on src/hooks/useCartItems/useCartItems.ts
> +  };
설명 감사합니다.

잘 이해가 안 되는데, 첫 번째 fetch에서 `20`이라는 인자를 넣어 불러오는 아이템의 수를 제한하고 있는데, 그 호출의 반환값에서 `totalElements`가 `20`이 넘을 수 있나요?

2024-05-31 00:58 UTC, zigsong commented on src/api/cart.ts
> +    endpoint: `/cart-items?size=${size}`,
`/api/cart.ts`에서 반복적으로 사용되는 endpoint인 `/cart-items/`를 별도의 상수로 빼두면 나중에 endpoint가 변경되거나 했을 때도 한번에 관리하기가 쉽겠죠?

2024-05-31 00:58 UTC, zigsong commented on src/assets/EmptyCart.png
앗 귀여운 배민 이미지가 있네요 ㅎㅎ

2024-05-31 00:58 UTC, zigsong commented on src/components/Button/Button.tsx
> +};
`Button` 컴포넌트도 딱 적당한 수준으로 사용성이 높게 잘 만드셨네요 👍

2024-05-31 00:58 UTC, zigsong commented on src/components/Dropdown/Dropdown.tsx
> +            </S.OptionItem>
Dropdown도 커스텀 스타일을 적용해주신 것을 보고 놀랐습니다! 

다만, `<li>` 태그나 `<input type="radio">`가 아닌 `<select>`, `<option>` 태그를 사용하셔야 합니다.

웹접근성을 고려하여 의미에 맞는 semantic HTML을 사용해주세요 :)

2024-05-31 00:58 UTC, zigsong commented on src/components/FloatingButton/FloatingButton.tsx
> +  );
무한스크롤을 대비하여 업버튼까지! 정말 세심하시네요. 저희팀으로 오시죠

2024-05-31 00:58 UTC, zigsong commented on src/components/ProductItem/ProductItem.tsx
> +          <h1>{name}</h1>
`<h1>` 태그는 지면 당 1개만 있는, 가장 중요한 타이틀을 의미합니다.

여기서는 `<h1>`은 어울리지 않겠죠? 🙃

2024-05-31 00:58 UTC, zigsong commented on src/context/ToastProvider.tsx
> +  const [isRemove, setIsRemove] = useState(true);
왜 `isOpen`과 `isRemove` 두 가지 상태로 별도로 관리해야 했나요? 👀

2024-05-31 00:58 UTC, zigsong commented on src/hooks/useIntersectionObserver.ts
> +  }, [callback]);
`IntersectionObserver`도 정석대로 잘 작성해주셨네요 😊

2024-05-31 00:58 UTC, zigsong commented on src/mocks/cartItem/cartItem.ts
> +  }),
delete 요청의 응답 status는 201이 아니라 204 아닌가요?

2024-05-31 00:58 UTC, zigsong commented on src/pages/ProductListPage/ProductListPage.style.tsx
> +  }
각 디바이스별로 꼼꼼하게 잘 챙겨주셨네요 👍

2024-06-01 07:34 UTC, chlwlstlf commented on src/hooks/useCartItems/useCartItems.ts
> +  };
![image](https://github.com/woowacourse/react-shopping-products/assets/63334368/e670e449-d91d-4d8c-ac40-89a6be4f901c)

totalElements는 사용자가 담고 있는 모든 아이템의 개수를 말합니다!
이 경우에서는 0페이지에 20개의 아이템, 1페이지에 2개의 아이템이 담겨있습니다. 
따라서 size를 22로 변경해서 다시 api를 요청하면 22개의 아이템을 모두 한번에 불러올 수 있습니다!🤗

6시 다돼서 타임어택으로 작성하다보니 설명이 많이 부족했네요..😭😭

2024-06-01 11:45 UTC, chlwlstlf commented on src/mocks/cartItem/cartItem.ts
> +  }),
아!!! 스웨거를 제대로 안 봤네요 수정하였습니다😊

2024-06-01 12:02 UTC, chlwlstlf commented on src/mocks/cartItem/cartItem.ts
> +  }),
`useCartItems` 훅에서 `handleDeleteCartItem` 로직은 다음과 같습니다. 
`handleDeleteCartItem`에서 `cartItems`와 `productId`로 해당 `cartItem`을 찾고 그 id로 api를 호출하는 방식입니다. 
```tsx
  const handleDeleteCartItem = (productId: number) => {
    const cartItem = cartItems.find((item) => item.product.id === productId);

    if (cartItem) {
      fetcher(async () => {
        await deleteCartItem(cartItem.id);
        await getCartItems();
      });
    }
  };
```
---
여기서 `cartItems`을 모킹하지 않아서 일치하는 `cartItem`을 찾지 못 하였고 api 호출도 되지 않았었습니다.
위의 코드에서 cartItems을 cartItems.json으로 모킹하는 코드를 추가하여 해결하였습니다.
```tsx
      act(() => {
        result.current.setCartItems(cartItemsData);
      });
```

2024-06-01 13:19 UTC, chlwlstlf commented on src/components/Header/Header.style.tsx
> +`;
`min-width: 435px;` 로 변경해서 다 채워지게 했습니다!

2024-06-01 13:32 UTC, chlwlstlf commented on src/pages/ProductListPage/ProductListPage.tsx
> +  );
저한테는 잘 뜨고 있는데 왜 이럴까요............😭😭

https://github.com/woowacourse/react-shopping-products/assets/63334368/9ce85677-2e2c-44e4-8456-60b8e26c4a1f

2024-06-01 16:32 UTC, chlwlstlf commented on src/hooks/useProducts/useProducts.ts
> +    setProducts(page === 0 ? data : [...products, ...data]);
0일 때도 배열로 받으면 카테고리를 바꿀 때 바꾼 카테고리들이 이전 결괏값 뒤에 추가됩니다.
따라서 page가 0일 때는 초깃값만 보여주어야 합니다!😀

2024-06-01 16:32 UTC, chlwlstlf commented on src/hooks/useCartItems/useCartItems.ts
> +    const { data: initialData, totalElements } = await fetchCartItems(20);
앗 놓쳤네요..! 수정하였습니다 :)

2024-06-01 16:36 UTC, chlwlstlf commented on src/assets/EmptyCart.png
리뷰어 맞춤...😎🥰

2024-06-01 17:29 UTC, chlwlstlf commented on src/api/cart.ts
> +    endpoint: `/cart-items?size=${size}`,
그렇네요!! endpoints 라는 폴더 만들어서 관리해주는 것으로 변경하였습니다!🤗

[b142f06](https://github.com/woowacourse/react-shopping-products/pull/4/commits/b142f0652690e177149e743ed7bc828a1cd39356)

2024-06-01 17:54 UTC, chlwlstlf commented on src/components/FloatingButton/FloatingButton.tsx
> +  );
> 저희팀으로 오시죠
> 저희팀으로 오시죠
> 저희팀으로 오시죠

제일 박력 넘친 리뷰..😮🤩

2024-06-01 18:14 UTC, chlwlstlf commented on src/context/ToastProvider.tsx
> +  const [isRemove, setIsRemove] = useState(true);
Toast가 뜰 때 뿐만아니라 사라질 때도 애니메이션을 주고 싶어서 만들었습니다!

`isOpen`이 `false`가 되면 사라지기 시작하고, 이때 서서히 Toast가 사라집니다.
애니메이션이 끝나는 시간과 비슷한 0.4초 후에 `isRemove`가 `true`가 되면서 Toast가 사라지게 됩니다.

혹시 더 좋은 방법이 있을까요..?? 반대되는 state를 둘 다 갖고 있지만 두 개의 역할은 달라서 리팩토링 할 방법이 떠오르지 않았습니다😂

2024-06-02 04:22 UTC, chlwlstlf commented on src/components/Dropdown/Dropdown.tsx
> +            </S.OptionItem>
이 부분이 드롭다운을 구현할 때마다 고민되는 부분이었는데요..
option 태그를 사용하면 css가 적용이 안 돼서 페이먼츠 미션 때는 피그마에 따라 어쩔 수 없이 다른 방법을 사용하였습니다.
지금은 피그마에 디자인이 따로 없어서 select와 option으로 변경하였습니다!

❓ option에 디자인을 넣어야 할 때는 어떤 방법을 사용할 수 있을까요??

2024-06-02 04:46 UTC, chlwlstlf commented on src/components/ProductItem/ProductItem.tsx
> +          <h1>{name}</h1>
> `<h1>` 태그는 지면 당 1개만 있는

이 부분은 처음 알았네요! 감사합니다😊

`<strong>`로 변경하였습니다!

2024-06-02 06:38 UTC, chlwlstlf commented on src/hooks/useProducts/useProducts.ts
> +  };
`useFilterAndSort.ts` 파일을 만든 후 필터링, 정렬 로직을 분리하였습니다. 그 후 `ProductListPage.tsx`에서 각 훅들을 호출하였습니다.😊
[7f42472](https://github.com/woowacourse/react-shopping-products/pull/4/commits/7f424722647459c2ba830eb93d5fb7b80d127c64)

2024-06-02 06:48 UTC, chlwlstlf commented
안녕하세요 지그!!😁 리뷰 빠르고 자세히 해주셔서 감사합니다👍👍🌸
(칭찬도 아낌없이 해주셔서 감사해요ㅎㅎㅎ!!)

## 설명
- 피드백 전부 다 반영하였습니다! 중요한 부분은 함께 달아 놓은 커밋 링크 있으니 확인해주세요!

- 버그를 찾지 못 하여 고치지 못 했습니다..! 어떨 때 생기는 지 알려주시면 감사하겠습니다 :)

- option에 어떻게 디자인을 적용 시켜야할 지 궁금합니다!
  https://github.com/woowacourse/react-shopping-products/pull/4#discussion_r1623323000

- Toast 애니메이션에 관리를 위한 state에 대해 질문이 있습니다!
  https://github.com/woowacourse/react-shopping-products/pull/4#discussion_r1623260850
  
저도 피드백을 빨리 반영하려고 했는데 훅 분리와 테스트 오류 해결에서 시간을 많이 써버렸네요..😭
1단계 리뷰 해주셔서 감사합니다🥰🔥

2024-06-03 10:46 UTC, zigsong commented on src/hooks/useCartItems/useCartItems.ts
> +  };
아하 `totalElements`값이 그런 거였군요~ 설명 감사합니다 :D

2024-06-03 10:50 UTC, zigsong commented on src/components/Header/Header.style.tsx
> +`;
여전히 다 채워지지 않고 있어 확인해보니, `<body>` 혹은 `<root>`에서부터 width가 꽉 채워지지 않고 있는 것 같습니다 

<img width="1720" alt="image" src="https://github.com/woowacourse/react-shopping-products/assets/44080404/66ef51a4-0511-49a3-9e33-fa2e857914e8">

2024-06-03 10:53 UTC, zigsong commented on src/pages/ProductListPage/ProductListPage.tsx
> +  );
이건 깃헙 버그인지 뭔지 이번엔 저와 텐텐이 코멘트에 첨부한 영상이 재생이 안 되네요 ;; 

설명을 드리면, A 카테고리에서 조회 > 무한스크롤로 추가 API 호출 후 다시 상단으로 와서 B 카테고리로 변경 

하면 상위 1개 또는 2개 아이템은 고정된 채 나머지 목록만 새로운 카테고리 목록으로 교체되는 현상이 있습니다.

2024-06-03 10:53 UTC, zigsong commented on src/hooks/useProducts/useProducts.ts
> +  };
훨씬 깔끔해졌네요 😉👍

2024-06-03 10:57 UTC, zigsong commented on src/components/Dropdown/Dropdown.tsx
> +            </S.OptionItem>
`<select>`와 `<option>` 태그가 마크업에는 존재하지만 실제 화면에는 보이지 않는 방식으로 구현을 하고, (CSS나 `aria-hidden` 등의 속성을 활용) 

실제로 디자인을 적용한 옵션 UI의 태그(`<div>` 등)에 `role="option'` 등의 속성을 추가하여 접근성까지 챙겨주시면 됩니다 :)

2024-06-03 11:01 UTC, zigsong commented on src/context/ToastProvider.tsx
> +  const [isRemove, setIsRemove] = useState(true);
`isOpen` 하나만 남겨두고, CSS의 `visibility: hidden` 또는 `display: block` 속성을 사용하시면 됩니다. 

`isOpen`과 `isRemove`는 서로 상반되는 의미의 상태라 한 쌍으로 관리하면 실수할 여지가 굉장히 많아요.

2024-06-03 11:03 UTC, zigsong requested changes
안녕하세요 텐텐~ 이미 잘하셨지만 리뷰 반영을 빠르게 잘 해주셔서 더욱 더 좋은 코드가 되었는데요, 

몇 가지 텐텐이 고쳐볼 수 있는 버그사항들이 있어 코멘트 남겼습니다. 

미션 요구사항에 있어서 치명적인 부분들은 아니라고 생각되어 다음 단계 진행을 원하시면 바로 머지하러 오겠습니다 😊

2024-06-04 01:46 UTC, chlwlstlf commented on src/pages/ProductListPage/ProductListPage.tsx
> +  );
키 값을 product.id로만 했었는데 중복되는 값이 있어서 저런 버그가 떴던 것 같아요....! (원래는 중복되는 값이 있으면 안 되는거죠??)

키 값을 {product.id}-{index} 변경해서 해결하였습니다!

2024-06-04 05:43 UTC, chlwlstlf commented on src/components/Header/Header.style.tsx
> +`;
html, body, #root의 width를 100vw로 했는데도 다 안 채워져서 어떻게 바꿔야할 지 모르겠습니다.. 100%로 해도 똑같았습니다!
2단계 때는 피그마 화면처럼 작게 바꿀 예정이라 이 부분과 관련이 없지만 무슨 오류인지 알고 싶네요😭

![image](https://github.com/woowacourse/react-shopping-products/assets/63334368/bf74e0ee-b9cd-48e5-94f5-ff83ee3f98ff)

제가 모바일로 확인했을 때는 우선 잘 나오는 상황입니다..!

---

![image](https://github.com/woowacourse/react-shopping-products/assets/63334368/94a5f3fc-e627-4cef-aaa4-626eb2444c9c)

width가 100vw인데 끝까지 안 차는 이유를 아직 못 찾았습니다.
혹시 지그도 이런 일을 겪으신 적이 있나요?? 어떻게 해결하셨는 지 질문드려도 되나요??🤗

2024-06-04 07:25 UTC, chlwlstlf commented on src/components/Dropdown/Dropdown.tsx
> +            </S.OptionItem>
`role` 태그를 사용하면 되는군요😮 이런 방법 처음 알았습니다!! 공부해서 적용해보겠습니다ㅎㅎㅎ

(이 부분 궁금해던 사람들이 많았어서 공유하였습니다! 감사합니다👍👍🤗)

2024-06-04 08:00 UTC, chlwlstlf commented on src/context/ToastProvider.tsx
> +  const [isRemove, setIsRemove] = useState(true);
`transition`과 `visibility` 사용해서 서서히 사라지는 것 구현하였습니다!
 isOpen 속성 하나로도 충분히 할 수 있었네요! 감사합니다🤩🤩
[eddd927](https://github.com/woowacourse/react-shopping-products/pull/4/commits/eddd927635fffb78199a35b62c3defa32321a00d)

2024-06-04 08:31 UTC, chlwlstlf commented
안녕하세요! 지그😊
치명적인 부분이 아니라고 하셨는데 치명적인 게 맞았..던 것 같아요😂😂 고칠 시간 주셔서 감사합니다!

## 수정된 부분
- 위쪽 아이템이 안 바뀌던 버그 해결하였습니다.
- toast에서 요소 사라지게 하는 것을 css로 관리하였습니다.

## 해결 못 한 부분
- 상위 요소를 모두 100vw로 해주었는데도 헤더가 아직도 꽉 차지 않습니다. 모바일에서는 잘 보이고 있어서 이 부분이 chrome의 오류인지 알아보고 있습니다.😭

2024-06-04 12:44 UTC, zigsong commented on src/components/Header/Header.style.tsx
> +`;
🤔🤔 요건 이상하네요. 제 설정 상의 문제일 수도 있어 넘어가겠습니다

2024-06-04 12:45 UTC, merged