[2단계 - 상품 목록] 라이언(박한영) 미션 제출합니다.
woowacourse/react-shopping-products pull request #49
Opened 2024-06-06 16:21 UTC by Parkhanyoung

2024-06-08 00:05 UTC, igy95 requested changes
안녕하세요 라이언~ 2단계 미션도 고생 많으셨습니다. 세부 코멘트 확인 부탁드리고 전반적인 피드백과 질문에 대한 답변 남기고 마무리할게요 :)

#### 전반적인 피드백

- `server` 폴더는 말 그대로 프론트엔드 내에서 따로 구축해둔 서버의 로직 등을 두는 폴더로 이해되기 때문에 현재 있는 코드를 고려해보았을 때 `api`, `queries`와 같은 폴더로 나누는 건 어떨까 싶네요!

#### useQuery의 staleTime의 구체적인 수치를 어떻게 정할지 감이 잡히지 않습니다 🥲

아직 사용 경험이 충분치 않아 그러신 듯 한데, 저라면 우선 tanstack query에서 제공하는 default option을 웬만하면 지키는 상태에서 아래의 방식대로 커스텀을 진행할 듯 싶습니다.

1. query 공통으로 옵션을 제공할 수 있는 영역과 query 개별로 옵션을 제공할 수 있는 영역을 두어 오버라이딩이 가능한 구조로 설계
2. 데이터 fetching과 관련한 특정 UX를 고민하는 시점에서 해당 쿼리의 옵션을 수정할 니즈가 있다면 수정

`staleTime`은 말 그대로 data의 신선도와 관련한 수치이기 때문에 따로 정립되어있는 규칙은 없으며, 이는 각 UX 내에서 적절한 데이터 처리를 위한 고민이 선행되어야 한다고 생각합니다.

때문에 지금은 이 옵션을 사용하는 여러 use case들을 아티클 등으로 찾아보면 좋을 것 같네요!

2024-06-08 12:30 UTC, Parkhanyoung commented on src/App.tsx
>      <>
수정 완료했습니다! [002faad](https://github.com/woowacourse/react-shopping-products/pull/49/commits/002faad468fdf5727d723b97fa8f11475c7cdc46)

2024-06-08 12:31 UTC, Parkhanyoung commented on src/server/queryClient.ts
> +      staleTime: 1000 * 60 * 5,
retry는 디버깅 도중 임시로 세팅했었던 것인데, 지우는 걸 잊었습니다 🥲 이 옵션은 지웠습니다! [eadbd4a](https://github.com/woowacourse/react-shopping-products/pull/49/commits/eadbd4a41bdd4a929be9d05c92301ddf0ba7e277)

상품 데이터는 게시글이나 댓글처럼 모든 유저가 자유롭게 생성하는 데이터는 아닌 만큼 자주 변경이 일어나지 않는다고 판단했습니다.
그렇다고 staleTime n시간 단위로 길게 하기에는 변경이 종종 발생할 수 있다고 판단하여 5분으로 정해보았습니다.

2024-06-08 12:32 UTC, Parkhanyoung commented on src/components/ProductFeedPage/CartItemQuantityController/index.tsx
> +// 명확한 정책이 없어서 임시로 99개로 설정
오 멘션해두면 다른 사람이 쉽게 저를 찾을 수 있겠군요! 반영 완료했습니다. [d2cbbe1](https://github.com/woowacourse/react-shopping-products/pull/49/commits/d2cbbe1e2660fbf77a29c8e924a92af68912337f)

2024-06-08 12:33 UTC, Parkhanyoung commented on src/components/common/LoadingSpinner.tsx
> +  if (!isLoading) return null;
카일의 코멘트에 동감하여 수정했습니다! [617521a](https://github.com/woowacourse/react-shopping-products/pull/49/commits/617521a2447d743349e0da6ba936c3fc6b9d2d51)

2024-06-08 12:46 UTC, Parkhanyoung commented on src/server/__constants__/queryKeys.ts
> queryKey와 mutationKey는 어떤 의도로 사용했는지

queryKey, mutationKey는 tanstack query가 각각의 데이터나 동작을 고유하게 식별할 수 있게 해주는 key라고 알고 있습니다. 이를 기반으로 캐싱이나 무효화 등의 동작이 수행됩니다. 그래서 각각이 id처럼 고유한 값을 가질 수 있도록 모두 다른 값으로 지정해 주었습니다. 단, cartItems와 cartAmount는 같은 queryKey를 지정해 주었는데, cartAmount는 cartItems 데이터를 기반으로 계산만 수행하기에 tanstack query가 동일 데이터로 식별해야 한다고 생각했기 때문입니다.

> 관련성이 강한 쿼리 간의 관계는 어떻게 관리하려고 하셨는지 설명 주시면 좋을 것 같습니다! (e.g. list query를 invalidate할 때 list에 해당하는 item query도 같이 invalidate해야 한다면?)

우선 특정 동작이 수행되었을 때 데이터 무효화가 필요하다면 onSuccess에서 무효화를 수행했습니다. 만약 특정 query를 invalidate할 때 연관 query도 같이 invalidate해야 한다면, invalidate를 담당하는 계층을 둘 것 같습니다. 예를 들면 invalidateList라는 함수를 선언하고 그 함수 내에서 list뿐 아니라 item에 대한 invalidate 로직도 함께 수행하는 식이 될 것 같습니다!

2024-06-08 12:59 UTC, Parkhanyoung commented on src/server/hooks/useCartAmount.ts
카일의 코멘트에 따라 수정해보았습니다! [875aaca](https://github.com/woowacourse/react-shopping-products/pull/49/commits/875aacad3937e35f0763903727331a147bba77f7)

그런데 한편으로는 select 옵션을 고려해보라고 하신 카일의 의도가 궁금하기도 합니다. 🙂
별도의 웹 요청이 필요하지 않으니 useQuery를 사용하기보다 기존의 방식처럼 이미 존재하는 useCartItems를 이용해 데이터를 받아오고 연산만 수행하여 반환하는 방식이 코드 상에서 의도가 더 명확히 드러나 보이기도 해서요! 이러한 생각에 대한 카일의 의견이 궁금합니다.

```ts
export const useCartAmount = () => {
  return useQuery({
    queryKey: [QUERY_KEYS.cartItems],
    queryFn: getCartItems,
    select: (cartItems) => calculateCartAmount(cartItems),
  });
};
```

```ts
export const useCartAmount = (): UseCartAmountReturn => {
  const { data: cartItems } = useCartItems();

  const cartAmount = calculateCartAmount(cartItems);

  return { cartAmount };
};
```

2024-06-08 13:08 UTC, Parkhanyoung commented on src/server/mutations/useUpdateCartItemMutation.ts
> +  const { mutate } = useMutation({
현재는 mutate만 사용하지만, 추후에 필요할 때 별도로 수정해주어야 한다는 점이 불편하겠네요! 좋은 부분을 짚어주셔서 감사합니다 👍🏻 카일의 코멘트에 따라 수정했습니다! [818ba1a](https://github.com/woowacourse/react-shopping-products/pull/49/commits/818ba1a805a6378ed048536047bc3d7c8079c36a)

2024-06-08 13:16 UTC, Parkhanyoung commented on src/server/queries/useCartItems.ts
> +  }, [error]);
사용처에서 다루도록 수정했습니다! [8aca1da](https://github.com/woowacourse/react-shopping-products/pull/49/commits/8aca1da65d521c732e44a2e75635aec1c633b4b0)

**Q. error boundary 사용과 관련해 질문 드리고 싶습니다.**
error boundary를 이용해 내부 컴포넌트들의 에러 핸들링을 한꺼번에, 그리고 선언적으로 처리하면 유지보수성에 도움이 되겠다고 생각하여 적용을 시도했습니다. 그런데 현재는 fallback ui가 아닌 토스트를 띄우는 방식으로 에러를 핸들링하고 있습니다. 그래서 fallback ui 없이 토스트를 띄우는 error handler만 넘겨 처리를 시도했습니다. 그런데 fallback prop을 넘기지 않으니 error boundary를 통해 정상적으로 에러가 핸들링되지 않았습니다. 혹시 error boundary로 fallback ui 없이 에러 핸들러(토스트나 alert를 띄우는 함수 등)만 실행하는 건 불가능한 것일까요? 혹은 이런 상황에서 error boundary 외에 에러 핸들링을 효과적으로 수행할 수 있는 다른 방법을 알고 계신다면 공유해주시면 큰 도움이 될 것 같습니다. 🙇🏻‍♂️

2024-06-08 13:35 UTC, Parkhanyoung commented
> server 폴더는 말 그대로 프론트엔드 내에서 따로 구축해둔 서버의 로직 등을 두는 폴더로 이해되기 때문에 현재 있는 코드를 고려해보았을 때 api, queries와 같은 폴더로 나누는 건 어떨까 싶네요!

server라는 네이밍은 서버 코드를 나타내는 데 쓰는군요! 짚어주셔서 감사합니다! :)
api 디렉토리는 fetch 계층을 나타내는 데 사용하고 있었고, queries 디렉토리는 기존 server 디렉토리 내부에서 mutations와 구분하기 위해 사용하고 있었어서, serverState라는 이름으로 수정해보았습니다. 카일이 보시기에 괜찮은 네이밍일지 여쭙고 싶습니다! (이름 짓는 게 가장 어렵네요.. ㅠ) [c29b8c5](https://github.com/woowacourse/react-shopping-products/pull/49/commits/c29b8c5c7c438478f7db07f7a043b68973b8e5b0)

2024-06-09 00:41 UTC, igy95 commented on src/server/queryClient.ts
> +      staleTime: 1000 * 60 * 5,
> 상품 데이터는 게시글이나 댓글처럼 모든 유저가 자유롭게 생성/수정하는 데이터는 아닌 만큼 자주 변경이 일어나지 않는다고 판단했습니다.

만일 이렇게 생각하셨다면, 쿼리 공통 영역이 아닌 상품 데이터와 관련된 쿼리 내에서만 이 옵션을 부여하는 게 맞을 듯 합니다. `queryClient` 내에 설정한 옵션을 개별 쿼리에서 오버라이딩 할 수는 있겠지만 이런 사실을 모르는 개발자가 작업할 경우 암묵적으로 쿼리의 stale time은 무조건 5분으로 설정될 것이기 때문입니다.

2024-06-10 23:53 UTC, igy95 commented on src/server/__constants__/queryKeys.ts
두 질문 모두 하나의 답변으로 드릴 수 있을 것 같아 통합하여 답변드리자면,

> 단, useCartItems와 useCartAmount은 같은 queryKey를 지정해 주었는데, cartAmount는 cartItems 데이터를 기반으로 계산만 수행하기에 tanstack query가 동일 데이터로 식별해야 한다고 생각했기 때문입니다.

적절한 방향이라고 생각하지만, tanstack query에서 제공하는 구조를 고려해보면 직접 재선언이 아닌 `useCartItems` 쿼리를 인용하여 `useCartAmount` 셀렉터 훅을 만들어주어도 충분할 것 같습니다. (오히려 이것이 더 권장되는 방향이기도 하구요.)

query key를 배열 형태로 두는 이유는 결국, 쿼리 간의 관계를 계층적으로 나타내어 상위 쿼리 키를 무효화하면 연관된 하위 쿼리는 자동으로 같이 무효화가 되도록 설계 되어있기 때문입니다.

라이브러리 원작자의 의도를 담은 [아티클](https://tkdodo.eu/blog/effective-react-query-keys)을 읽어보시면서 적절한 쿼리키 사용 방식에 대해 좀 더 확인해보면 좋겠네요!

2024-06-11 00:03 UTC, igy95 commented on src/server/hooks/useCartAmount.ts
어느 한쪽이 명확한 장점이 있다기보다는, 이러한 옵션도 있으니 쿼리를 hook으로 감싸 그 안에 데이터 가공 로직을 두는 방식과 `select` option을 사용했을 때 차이를 비교해보시면 좋겠다는 측면이었습니다.

코멘트가 너무 특정 라이브러리 위주로 진행되는 듯하여 이 부분은 라이언이 직접 찾아보시면 좋을 듯 합니다. (라이브러리 관련 질문과 논의는 해당 레포에서 많이 이뤄지니 한번 봐보시면 좋겠네요 [#](https://github.com/TanStack/query/discussions/3353))

2024-06-11 00:12 UTC, igy95 commented on src/server/queries/useCartItems.ts
> +  }, [error]);
에러 바운더리의 메커니즘에 대해 좀 더 찾아보면 좋을 것 같습니다. `render` 단에서 `fallback` 대신 `children`을 반환하면 계속 문제가 발생하는 컴포넌트가 렌더링 되지 않을까요?

2024-06-11 00:14 UTC, igy95 approved these changes
안녕하세요 라이언~! 마지막 미션도 고생 많으셨습니다 :) 라이브러리를 사용하시면서 여러 궁금증이 생기셨던 것 같네요. 리뷰 반영 사항과 추가 질문 주신 부분 확인하여 코멘트 남겨두었으니 확인 부탁드립니다!

해당 미션은 여기서 머지하도록 할게요

2024-06-11 00:14 UTC, merged