[2단계 - 상품 목록] 버건디(전태헌) 미션 제출합니다.
woowacourse/react-shopping-products pull request #55
Opened 2024-06-08 08:44 UTC by brgndyy

안녕하세요 카일 이번에 step2로 뵙게 되었네요!

날이 갑자기 많이 더워지는데, 감기 조심하시길 바랍니다! (목, 코감기가 유행이더라구요)

우테코에서의 마지막 코드리뷰네요. 

따로 질문 드릴 부분은 코멘트로 남겨놓도록 하겠습니다!

마지막 코드 리뷰 잘부탁드립니다 🙇

2024-06-08 09:12 UTC, brgndyy commented on src/App.tsx
> +      staleTime: 1000 * 20,
쿼리 내부에서 default stale 타임이 0초더라구요..!

그래서 따로 20초로 설정을 일단 해주어보았는데요.

카일만의 stale 타임을 지정하는 기준이 있으실까요 ?

가령 이번 미션을 예로 들어보자면 (개인 쇼핑몰 사이트라고 가정해보겠습니다.)

1. 개인 쇼핑몰이며, 어드민측에서 상품을 따로 직접 업로드하지 않는다면 보여지는 상품 목록은 항상 같다.
2. 그래서 어드민 측에서 상품 등록하는 페이지에서 '상품 등록' 버튼을 눌러서 상품 목록 추가 post 요청을 할때, 상품 목록을 불러오는 query-key 를 무효화 해주어서 새로운 데이터를 받아온다.

이렇게 된다면, 항상 상품목록을 가져오는건 stale 타임을 infinity로 두어도 상관없지 않나? 라는 생각이 들기도 했습니다.

그리고 `category`나 `sortType` 상태값이 변하는 이벤트가 발생했을때, 이미 받아온 전체적인 상품 목록 데이터에서 filtering을 해주는것이 api콜을 최소화 할수 있는 방법 아닐까? 라는 생각도 들었습니다.

근데, 리액트 쿼리를 사용하면서 받아온 데이터를 또 로컬 state 상태로 두는것이 안티패턴으로 알고 있는데, 이 원칙에 위반하지 않나? 라는 의구심도 들었고요..!

정리해보자면

1. 목록이 딱히 변하지 않는 경우, stale타임을 infinity로 두어도 괜찮지 않나?
2. 리액트 쿼리로 받아온 서버 상태를, 로컬 state 상태로 받아와도 상관 없나 ?


이 정도로 정리해볼수 있을거 같습니다!

2024-06-08 09:12 UTC, brgndyy commented on src/hooks/useProductList.ts
> +    useSuspenseInfiniteQuery({
이번에 에러바운더리처리를 위해서 `useInfiniteQuery`가 아니라, `useSuspenseInfiniteQuery`를 사용해주었는데요.

useQuery 또한, 일반 useQuery와 useSuspenseQuery가 나누어져있더라구요!

제가 현재까지 공부해본 것은 , Suspense를 적용시키기 위해서 `useSuspenseQuery`가 탄생했지만, enabled 옵션 같이 쿼리를 섬세하게 다루기 위해서는 `useQuery`를 사용해야한다. 입니다.

단순히 여기서 `Suspense`를 사용하려면 `useSuspenseQuery`를 사용해야한다. 

로 인식을 가져가야할지, 아니면 제가 놓치고 있는 부분이 있을지 여쭈어보고 싶습니다.

2024-06-08 09:12 UTC, brgndyy commented on src/provider/CartItemProvider.tsx
이번에 리액트 쿼리를 사용하면서, 자연스럽게 Context를 없애게 되었는데요.

리액트 쿼리에서 제공해주는 캐싱데이터를 사용하다보니, 여러 컴포넌트에서 그냥 동일한 쿼리키를 가진 쿼리 데이터를 불러오는 것이 더 간편하겠다고 생각했습니다.

근데 이렇게 되면, `전역 상태`라는 것이 많이 존재할 필요가 있나? 라는 의구심이 듭니다.

제가 실제로 겪어온 전역상태의 예는, 테마값, 로그인을 위한 토큰 쿠키 값이었는데요.

근데 이 또한 그냥 전역 상태 라이브러리를 사용하지 않고, 컨텍스트만으로도 값을 충분히 관리해줄수 있지 않을까 싶습니다..! 

이 2개의 값 이외에 전역적으로 값을 사용해야할 예시가 있을지 한번 여쭈어보고싶습니다.

2024-06-09 00:38 UTC, igy95 requested changes
안녕하세요 버건디! 이번에 쿼리 적용하시면서 에러 바운더리, 서스펜스 등 여러 부분을 학습 및 적용해보려고 하신 듯 하네요~ 이와 관련해서 질문 주신 부분과 코멘트 필요한 부분에 달아두었으니 확인 후 재요청 부탁드립니다 😀

2024-06-09 00:38 UTC, igy95 commented on src/components/common/Image/Image.tsx
> +}
그냥 `img` 태그를 쓰는 것과 다를 게 없지 않을까요? 👀

2024-06-09 00:38 UTC, igy95 commented on src/queries/keys.ts
이 부분은 v5 공식 문서의 query key 섹션 하단 항목 ([#](https://tanstack.com/query/latest/docs/framework/react/guides/query-keys#further-reading)) 링크를 읽어보시면 도움이 되겠네요 !

2024-06-09 00:38 UTC, igy95 commented on src/App.tsx
> +      staleTime: 1000 * 20,
> 목록이 딱히 변하지 않는 경우, stale타임을 infinity로 두어도 괜찮지 않나?

저도 동의하는 편입니다. 다만 어떠한 데이터가 '앞으로도' 변하지 않을 것이라 확신을 하는 것은 재고해보는 것이 좋을 듯 해요. 데이터 최신화를 고려하지 않은 캐싱은 몇가지 문제를 야기할 수 있습니다. 가령,

1. 재고가 소진되어 상품 데이터를 sold out 처리하였는데, 사용자의 화면에서는 이 처리가 되지 않아 그대로 주문이 가능하다면?
2. pagination으로 api가 내려오는 상황이라 카테고리, 정렬과 같은 로직도 백엔드에서 담당해야 한다면? (만일 이러한 상황에서 클라에서 처리를 한다면 단일 페이지 단위로만 필터링이 가능하거나 페이지 단위로 받아온 데이터를 모두 들고 있어야 하기 때문에 계산 비용 증가)

이러한 이유로 우선은 라이브러리 제작자의 입장에서 왜 default time을 0으로 두어 무조건적인 최신화를 지향했는지, 버건디가 설정하신 20초에 대한 근거는 어디서 기반한 건지에 대한 정립이 먼저라고 생각해요.

2024-06-09 00:38 UTC, igy95 commented on src/App.tsx
> +      staleTime: 1000 * 20,
> 리액트 쿼리를 사용하면서 받아온 데이터를 또 로컬 state 상태로 두는것이 안티패턴으로 알고 있는데, 이 원칙에 위반하지 않나? 라는 의구심도 들었고요..!

하나로 귀결되는 답이 있다기 보다는, 상태를 추가할 때 기존에 들고 있는 상태로 대체 가능한 것이 없는가에 대한 고민을 항상 해보시면서 코드를 작성하시면 될 것 같습니다.

2024-06-09 00:38 UTC, igy95 commented on src/hooks/useProductList.ts
> +    useSuspenseInfiniteQuery({
이런 부분은 공식문서, github으로 충족되지 않는다면 작은 코드 내에서 실험을 해보시는 것도 좋을 듯 합니다. `useQuery`를 사용하면 `Suspense`를 사용하지 못할까요? `useQuery`를 그냥 사용하거나 내부에 `suspense: true` 옵션을 선언할 때, `useSuspenseQuery`, `enabled` 옵션을 부여한 쿼리를 사용해보면서 어떤 차이가 있을지 공유 주시면 좋을 것 같습니다.

2024-06-09 00:38 UTC, igy95 commented on src/provider/CartItemProvider.tsx
실제로 api로 받아온 데이터를 '서버 상태'라는 패러다임으로 전환한 이상, 이것을 더이상 앱 단에서 들고 있을 필요가 없어졌고 그로 인해 대부분의 전역 상태는 사라졌다고 생각합니다. 그래서 말씀 주신 부분에 한정된 경우도 있을 거 같기도 하구요. 다만 context api 만으로 전역 상태를 다루기엔, 하위 컴포넌트의 리렌더링 범위와 상태 추적 도구의 부재 등 여러가지 리스크를 감수해야할 것 같습니다.

현재 만들고 있는 규모에서는 필요성을 못느낄 수 있지만 이보다 더 복잡한 앱을 만들게 될 경우 tanstack query를 사용해도 전역 상태 관리의 니즈는 충분히 생길 수 있을 것 같아요~

2024-06-09 00:38 UTC, igy95 commented on src/api/Fetcher.ts
> +      }
이러한 분기 처리가 모든 api마다 반복이 될 것 같은데, 분기 처리를 에러 바운더리 혹은 에러 fallback 쪽에서 할 수 있는 방법은 없을까요?

2024-06-09 00:38 UTC, igy95 commented on src/hooks/useDeleteCartItem.ts
> +const DEFAULT_TOAST_DURATION = 2_000;
이 상수가 다른 곳에서도 중복 선언 되어 있는 것으로 보이는데, 각 사용처마다 토스트의 노출 기간을 설정해야하는 이유가 있을까요?

2024-06-09 14:36 UTC, brgndyy commented on src/api/Fetcher.ts
> +      }
짚어주셔서 감사합니다. 🙇 

이와 관련한 궁금증이 들어서 `QueryErrorBoundary` 파일에 코멘트 추가해보았습니다!

2024-06-09 14:36 UTC, brgndyy commented on src/components/Error/QueryErrorBoundary.tsx
말씀대로 `Fetcher` 내부에서는 error를 throw만 해주고 `QueryErrorBoundary` 컴포넌트 내부에서 분기처리를 해주고 있는데요.

커스텀한 `HttpError`와 일반 Error 의 instanceof 를 나누어서 처리해주고 있습니다.

HttpError를 따로 만들어준 이유는 status를 명시적으로 받아와서 표시해주기 위함이었는데요.

카일이 의도하셨던 부분이 이런식의 처리 흐름이 맞을지 여쭤보고 싶습니다.

2024-06-09 14:36 UTC, brgndyy commented on src/components/common/Image/Image.tsx
> +}
에구 맞습니다..! 

짚어주셔서 감사합니다 :) 수정하였습니다.

2024-06-09 14:36 UTC, brgndyy commented on src/hooks/useProductList.ts
> +    useSuspenseInfiniteQuery({
v5로 넘어오면서 `suspense:true` 옵션은 deprecated가 되어서 suspense를 사용하기 위해선 `useSuspenseQuery`나 `useSuspenseInfiniteQuery`를 사용해야하는 것으로 알고 있습니다! 

대신에 조건적으로 쿼리를 가져올수 있는 `enabled`속성은 사용할수 없다고 공식문서에 적혀있더라구요.

<img width="378" alt="스크린샷 2024-06-09 오후 11 29 32" src="https://github.com/woowacourse/react-shopping-products/assets/109535991/06653a9d-4654-4283-acce-4236532665dc">

단순히 로딩 상태를 선언적으로 나타내기 위해서, 쿼리를 섬세하게 다룰수 있는 옵션을 포기해야할지..

이 트레이드 오프에서 어떠한 기준점을 잡아야할지 감이 안잡혀서 카일의 의견 한번 여쭙습니다!

2024-06-09 14:36 UTC, brgndyy commented on src/hooks/useDeleteCartItem.ts
> +const DEFAULT_TOAST_DURATION = 2_000;
짚어주셔서 감사합니다! 수정하였습니다.

2024-06-11 00:39 UTC, igy95 commented on src/hooks/useProductList.ts
> +    useSuspenseInfiniteQuery({
아 v5로 넘어오면서 제가 알고 있던 것과 조금 상이한 부분이 있었네요 🥲 저라면

- 데이터를 무조건 fetching 해와야 하고 Suspense를 사용함이 보장되는 환경이라면 -> `useSuspenseQuery`
- 특정 분기 조건에 따라 데이터 fetching을 하지 않을 수도 있다면 -> `useQuery`

를 사용할 것 같습니다. 다만 v5로 넘어오면서 `useQuery`에서 `Suspense`를 사용하려면 수동으로 promise를 던져야 하는 것으로 보이는데 이러한 의도에 대해서는 저도 조금은 의문이네요 🤔

2024-06-11 00:43 UTC, igy95 commented on src/components/Error/QueryErrorBoundary.tsx
`QueryErrorBoundary`는 에러 바운더리 + tanstack query를 결합하는 레이어이기 때문에 기본적인 에러 핸들링 로직은 `ErrorBoundary` 내에 들어가는 게 맞지 않을까 싶습니다. `HTTPError` 등의 분기 처리는 에러 핸들링 정책에 따라 나뉠 수 있는 부분이기 때문에 사용자가 인지만 가능하다면 그대로 가져가도 괜찮을 듯 싶네요!

2024-06-11 00:44 UTC, igy95 approved these changes
안녕하세요 버건디! 리뷰 반영하시느라 수고 많으셨습니다. 코멘트 상에서 추가 질문 주신 부분에 대한 답변 남겨두었으니 확인 부탁드리고 해당 미션은 이만 머지하도록 할게요~!

2024-06-11 00:44 UTC, merged