[2단계 - 상품 목록] 제이드(전세영) 미션 제출합니다.
woowacourse/react-shopping-products pull request #71
Opened 2024-06-09 18:00 UTC by skiende74

안녕하세요 케빈 ! 이번에 2단계 구현을 완료했습니다. 
마지막 미션이라 시원섭섭하네요 ㅎㅎㅎ

리뷰 해주셔서 감사드립니다.

## 구현사항
- react-query로 서버실패 상태에대한 로직 구현
- 비동기 테스트
- 지난미션에서 만든 모달을 활용하여 장바구니모달
- api호출 공통로직 ApiClient로 리팩토링

더 해보고싶은것
 - 저속 네트워크 환경에서의 UX개선. (react-query 낙관적 렌더링, 로딩 등)

#### 1단계 기다리면서 추가로 해봤던 것
#21 
의 PR에 있습니다 :)

2024-06-11 12:17 UTC, JeongBin0227 commented
![image](https://github.com/woowacourse/react-shopping-products/assets/45503248/d074ea68-5982-49f2-95d4-267face2a286)

여기는 담기 버튼이 없네요 버그일까요?

2024-06-11 12:17 UTC, JeongBin0227 commented
![image](https://github.com/woowacourse/react-shopping-products/assets/45503248/57d0e50a-bd07-40c5-aff1-1c396637d7e9)

이미지가 없는 경우를 대비해서 디폴트 이미지를 보여주게 바꿔보면 어떨까요?

2024-06-11 12:22 UTC, JeongBin0227 requested changes
안녕하세요 제이드~

1차적으로 전체 코드와 배포된 주소 보면서 리뷰 남겨드렸습니다! 코드에 대한 코멘트는 일부만 남겼는데, 비슷한 코드에 대해서 전체적으로 수정해보시면 좋을거 같아요! 혹시 이해가 안되는 코멘트가 있으면 알려주세요~

2단계 미션하느라 고생하셨습니다 💯

2024-06-11 12:22 UTC, JeongBin0227 commented on src/api/ApiClient.ts
> +      throw new Error(`200~299 이외의 응답이 발생하였습니다.${response.body}`);
response.body 이렇게 접근이 되시나요? 해당 구문은 ReadableStream 이라서  .text() 또는 .json()으로 처리되어야 할거 같아요

2024-06-11 12:22 UTC, JeongBin0227 commented on src/api/ApiClient.ts
> +      throw new Error(`200~299 이외의 응답이 발생하였습니다.${response.body}`);
```
if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`HTTP error! status: ${response.status}, message: ${errorText}`);
      }
```
보통 이렇게 처리 많이 합니다

2024-06-11 12:22 UTC, JeongBin0227 commented on src/components/CartModal/CartItemCard.tsx
> +  cartItem: CartItem;
style도 props 으로 받고있으니
```
style?: React.CSSProperties;
```
추가 해보면 어떨까요

2024-06-11 12:22 UTC, JeongBin0227 commented on src/components/CartModal/CartItemCard.tsx
> +const CartItemCard = ({ cartItem, style }: CartItemProps) => {
여기서 추가로 
```
const CartItemCard = ({ cartItem, style, ...props }: CartItemProps) => {
이렇게 해주면

아래에서
<div style={style} {...props}>

이렇게 사용해주면서 더 커스텀이 다양하게 쓰일수 있어요
```

2024-06-11 12:22 UTC, JeongBin0227 commented on src/components/CartModal/CartItemCard.tsx
> +              }}
이렇게도 바로 쓸수 있어요
```
 onClick={() => deleteToRemoveCart(cartItem.id)}
```

2024-06-11 12:22 UTC, JeongBin0227 commented on src/components/ProductList/ProductCard/ProductCard.tsx
> +  const cartItem = cartItems?.filter((item) => item.product.id === product.id)[0];
cartItem을 찾기위해만 사용하는거면 filter 대신 find 메서드를 사용하는 것이 더 효율적일거 같아요
```
  const cartItem = cartItems.find((item) => item.product.id === product.id);
```

2024-06-11 12:22 UTC, JeongBin0227 commented on src/api/ApiClient.ts
> +}
API 를 많이 만들다 보면, 반복되는 코드가 있기 마련입니다.
지금 처럼 header 가 될수도 있고, 에러 로직일수도 있고.. 저는 그럴때마다 api interceptor 를 사용해서 반복되는 코드를 줄여보는걸 권장해드려요.
인스턴스를 만들어서 해당 api 의 반복되는 코드를 줄이고, 코드를 일관되게 만들수 있을거 같아요

https://woojeongmin.com/2022/intercept-fetch-api/ 참고해보면 좋을거 같습니다

2024-06-11 12:22 UTC, JeongBin0227 commented on src/components/common/Stepper/Stepper.tsx
> +};
이런식으로 아이콘을 쓰는 경우라면 차라리 iconbutton 컴포넌트를 만들어서
```
const IconButton = ({ onClick, imgSrc, $isActive }: ButtonProps & { imgSrc: string }) => (
  <RoundButton width={28} height={28} onClick={onClick} $isActive={$isActive}>
    <CenteredDiv>
      <StyledImage src={imgSrc} />
    </CenteredDiv>
  </RoundButton>
);
```
이를 활용해서

```
const PlusButton = (props: ButtonProps) => <IconButton imgSrc={PlusSign} {...props} />;
const MinusButton = (props: ButtonProps) => <IconButton imgSrc={MinusSign} {...props} />;
```
이렇게 쓰는게 훨씬 재사용성이 좋을거 같아요

2024-06-11 12:22 UTC, JeongBin0227 commented on src/components/common/Stepper/Stepper.tsx
> +    <div>
여기 div가 필요있나요?

2024-06-11 12:22 UTC, JeongBin0227 commented on src/hooks/useFetchCart.ts
> +    isPending,
isPending 보다는 isLoading 이 어떨까요?
isLoading 이라는 단어를 많이 활용하긴 합니다

2024-06-12 01:54 UTC, skiende74 commented
> ![image](https://private-user-images.githubusercontent.com/45503248/338578273-d074ea68-5982-49f2-95d4-267face2a286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTcyMTgsIm5iZiI6MTcxODE1NjkxOCwicGF0aCI6Ii80NTUwMzI0OC8zMzg1NzgyNzMtZDA3NGVhNjgtNTk4Mi00OWYyLTk1ZDQtMjY3ZmFjZTJhMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxNDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZTI2MTM1MWMzZjkzYTc2MDAzZTZmNjNhMmFjMDc3M2IwYjFjNTUwNmU3ZDRkYzZlMzdkYTBjNDVhNGU4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CzgoXiG1mimNPRAcwm73ezXPs3ZUlvlYoEpsoDhW1OQ)
> 
> 여기는 담기 버튼이 없네요 버그일까요?

![image](https://github.com/woowacourse/react-shopping-products/assets/86130706/bb8abda4-5872-4e1d-9308-a1644487f21d)
밑에있습니다 !

2024-06-12 02:00 UTC, skiende74 commented
> ![image](https://private-user-images.githubusercontent.com/45503248/338578356-57d0e50a-bd07-40c5-aff1-1c396637d7e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTc1NTUsIm5iZiI6MTcxODE1NzI1NSwicGF0aCI6Ii80NTUwMzI0OC8zMzg1NzgzNTYtNTdkMGU1MGEtYmQwNy00MGM1LWFmZjEtMWMzOTY2MzdkN2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxNTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ODYzODJjNDJlMTMwZDk0ODQ0NDUyY2FmN2I2MTk0Y2M1YTM4MTRhMmVlMTQyZDUwMWM4ZDIyNTdjYjkxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zdFuDyaJPDx4ISJIl4_R62wr6o3cH7Q9rp5LhRAbQ8I)
> 
> 이미지가 없는 경우를 대비해서 디폴트 이미지를 보여주게 바꿔보면 어떨까요?

이미지가 없는 경우를 위해 디폴트 이미지를 넣어보았습니다

2024-06-12 02:01 UTC, skiende74 commented
> 2024-06-11.9.18.32.mov 
> 이렇게 이중으로 스크롤 되는 버그가 있는거 같아요~

음 이건 마우스포인터가 모달위에있을땐 모달을 스크롤하고
모달 밖에서 스크롤하면 밖을 스크롤하게 의도한거였는데

모달내부로만 스크롤하는게 나을까요?
고쳐보겠습니다

2024-06-12 02:03 UTC, skiende74 commented on src/api/ApiClient.ts
> +      throw new Error(`200~299 이외의 응답이 발생하였습니다.${response.body}`);
> response.body 이렇게 접근이 되시나요? 해당 구문은 ReadableStream 이라서 .text() 또는 .json()으로 처리되어야 할거 같아요

.body가 객체라서 제대로 출력이 안되겠네요
고쳐보겠습니다.

2024-06-12 02:12 UTC, skiende74 commented on src/components/CartModal/CartItemCard.tsx
> +  cartItem: CartItem;
음 Props가 React.HtmlAttributes를 상속(확장)하고있는데
style?: CSSProperties | undefined;가 이미 존재해서 
HTML 기본 attribute를 사용할 때 이걸 Prop에서 다시 override 해주는 것이 오히려 좋지않다고 생각했었는데 
혹시 더 자세히 알 수 있을까요?

2024-06-12 02:14 UTC, skiende74 commented on src/components/CartModal/CartItemCard.tsx
> +              }}
싫어하는 분이 있을까 싶어서 번거로워도 {}로 감싸주었었는데
저도 이렇게 하는 걸 좋아해서 앞으로 이렇게해야겠네요 ㅎㅎ

2024-06-12 02:14 UTC, skiende74 commented on src/components/CartModal/CartItemCard.tsx
> +              }}
이건 다른 내용이지만 
혹시 케빈은 early return 하실 때
한줄로 써주시나요? 중괄호를 써주시나요? 

if (조건) return;
if (조건) {
return;
}

2024-06-12 02:15 UTC, skiende74 commented on src/components/ProductList/ProductCard/ProductCard.tsx
> +  const cartItem = cartItems?.filter((item) => item.product.id === product.id)[0];
더 좋은거같습니다.

2024-06-12 02:18 UTC, skiende74 commented on src/components/common/Stepper/Stepper.tsx
> +};
감사합니다

2024-06-12 02:55 UTC, skiende74 commented on src/hooks/useFetchCart.ts
> +    isPending,
useQuery의 리턴 속성 isPending을 사용하되,
변수명은 isLoading으로 명명하라는 말씀이실까요?

useQuery의 리턴속성 isPending대신 isLoading 속성을 사용하는게 좋을 것 같다는 말씀이실까요?

2024-06-12 03:47 UTC, skiende74 commented on src/api/ApiClient.ts
> +    }
그러면 Error객체에 Error.status 속성을 추가한 것을
ResponseError 로 타입정의한 뒤 비즈니스로직에서 사용할때는 이 status속성에 접근하면 괜찮을까요?

아니면 케빈은 interceptor를 직접 만들어서 onError로 사용하는 걸 선호하시는 편인가요?

2024-06-13 04:58 UTC, skiende74 commented on src/components/common/Stepper/Stepper.tsx
> +    <div>
제거하였습니다 :)

2024-06-13 08:43 UTC, skiende74 commented on src/api/ApiClient.ts
> +}
추상화를 할 때, 유연성을 잃게 되는 경우 찝찝한 마음을 갖게되는 것 같습니다.
interceptor를 이용해 좀 더 유연함을 가질수 있어서 좋을 것 같네요
interceptor를 구현해보았습니다.
[c2abb69](https://github.com/woowacourse/react-shopping-products/pull/71/commits/c2abb6930d21300352b3e7939776191dee82167b)

2024-06-13 08:47 UTC, skiende74 commented
안녕하세요 케빈.
리뷰주신 사안에 대해 적용해보았습니다.

주된 변경사항
- interceptor 구현
- RoundButtonWithImg : props 변경 시에 자동 반영되게 함

2024-06-14 03:03 UTC, JeongBin0227 commented on src/api/ApiClient.ts
> +    }
> '4xx대 에러가 발생했을때, 에러코드가 401이냐, 404이냐에따라
> 다른 처리를 해주고싶은 경우가 많다.
> 그래서 HTTP 상태코드도 어떤식으로든 넘겨서 알수있게해줘야한다'
> 이렇게 해석했는데 맞을까요?

네 맞습니다. 그래서
status속성에 접근하면 괜찮을까요? 이방법도 괜찮고 onError 에서도 좋은거 같아요 뭔가 상황에 맞게 사용하시면 될거같아요.
예를 들어 화면단 조작이 필요없을때 (바로 에러페이지로 이동) onError 에서 처리하면되고, 화면단 수정이 필요하면 status 를 활용하여 수정하면 될거 같아요~

2024-06-14 03:06 UTC, JeongBin0227 commented on src/components/CartModal/CartItemCard.tsx
> +  cartItem: CartItem;
흠 처음 적은 의도는 보통 공통적인 컴포넌트를 만들고, 사용하는곳에서 커스텀하게 색상을 바꾸는 경우가 필요하다고 생각했습니다.
그래서 style 이 있으면 좋겠다고 1차적으로 생각했는데, 제이드 말대로 React.HtmlAttributes 가 이미 상속하고 있으니 이부분은 필요없을거 같아요~ 👍 놓친부분 알려주셔서 감사합니다

2024-06-14 03:07 UTC, JeongBin0227 commented on src/components/CartModal/CartItemCard.tsx
> +const CartItemCard = ({ cartItem, style }: CartItemProps) => {
저는 보통 모든 컴포넌트에서 사용해주는 편입니다. 왜냐하면 어떻게 사용할지도 모르고 제가 공통컴포넌트를 만들었지만, 다른 사람들이 쓰는 경우도 많아 최대한 자유롭게 열어주려고 하는편입니다

2024-06-14 03:07 UTC, JeongBin0227 commented on src/components/CartModal/CartItemCard.tsx
> +              }}
이런건 사실 팀 컨벤션을 따르려고 하는 편입니다. 팀컨벤션에 따라 프리티어로 수정해둬서 사용하는데 저희팀에서는
후자를 사용합니다~
```
if (조건) {
return;
}
```

2024-06-14 03:08 UTC, JeongBin0227 commented on src/api/ApiClient.ts
> +}
의도한대로 잘 구현된거 같아요!

2024-06-14 03:09 UTC, JeongBin0227 commented on src/hooks/useFetchCart.ts
> +    isPending,
네 맞습니다. 이 부분은 제가 슬랙에서랑 다르게 말씀드렸는데,

useQuery의 리턴속성 isPending대신 isLoading 속성을 사용하는게 좋을 것 같다는 말씀이실까요?
-> 이쪽이 더 맞는 의도인거 같아요.
isPending을 쓰는경우를 잘못봐서 찾아봤는데, 이런 차이가 있다고 하네요!
https://velog.io/@qkrthdus605/React-Query-useQuery-isLoading-vs-isFetching

2024-06-14 03:11 UTC, JeongBin0227 commented
> 이건 사실 일부러 의도한 거였는데,
> 마우스포인터가 모달위에있을땐 모달을 스크롤하고
> 모달 밖에서 스크롤하면 밖을 스크롤 하게 하였었습니다.
> 
> 모달내부로만 스크롤하는게 나을까요?
> 고쳐보겠습니다
> 
> 지금은 아니라도, 모달이 떴을때 유저입장에서 바깥을 스크롤하고싶은 경우도 있을까요?
> 만약 그런경우라면 바깥화면의 dimming은 꺼주면 좋겠다고 생각했는데 적절히 생각한 걸 까요?

이게 의도된 기능이라면 괜찮습니다. 하지만 저는 이미 모달을 보고있는데 외부 스크롤이 되는게 어색하게 느껴진거 같아요.
유저입장에서는 모달을 보며, 모달 내부 스크롤을 하고있는데, 외부가 스크롤되면 당황할거 같기도 하고 바깥을 보고 싶으면 끄고 확인할거 같아요
저의 개인적인 입장입니다.. ㅎㅎ

2024-06-14 03:12 UTC, JeongBin0227 requested changes
안녕하세요 제이드!

슬랙으로도 질문 주셨는데, 다소 늦게 확인하여 죄송합니다 ㅠㅠ 수정된 부분이나 코멘트 주신부분 모두 확인하였습니다. 충분히 머지할만한 코드이지만, 한번더 Request changes로 드릴테니, 더 추가로 봐주면 좋겠는 부분이 있으면 알려주셔도 좋고, 아니라면 가볍게 읽고 다시 리뷰 요청부탁드려요~

2단계 미션하느라 고생하셨습니다 💯 저도 리뷰하면서 고민을 많이해봐서 좋은 시간이었습니다.

2024-06-14 21:15 UTC, skiende74 commented on src/hooks/useFetchCart.ts
> +    isPending,
음 일단 isPending으로 한 이유는, 공식문서에 모든 예시가 isPending으로만 되어있어
권장하는 방식이라 판단하여 그렇게하였습니다.
[Queries - 공식문서](https://tanstack.com/query/latest/docs/framework/react/guides/queries)
[QuickStart - 공식문서](https://tanstack.com/query/latest/docs/framework/react/quick-start)
[Overview - 공식문서](https://tanstack.com/query/latest/docs/framework/react/quick-start)

isLoading과 isPending의 사용처 구분은
보편적인경우에 isPending을 사용하고, 
lazy query를 이용해 로딩스피너를 만들때 isLoading을 만들라는 것으로 해석이 되었습니다.
> If you are using disabled or lazy queries, you can use the isLoading flag instead. 

[isLoading - 공식문서](https://tanstack.com/query/latest/docs/framework/react/guides/disabling-queries#isloading-previously-isinitialloading)

---

isPending과 isLoading 차이는 올려주신 글에서도 나오는 내용인데
react-query v4에서까지의 isLoading이 v5에서 isPending으로 변수명이 변경되었습니다.
![image](https://github.com/woowacourse/react-shopping-products/assets/86130706/486b4434-f8fe-4f67-9d85-f86d1e9bed80)
[ isLoading -> isPending 공식문서 ](https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5)
[ status-checks-in-react-query 공식문서 ](https://tanstack.com/query/latest/docs/framework/react/community/tkdodos-blog#4-status-checks-in-react-query)

v4 -> v5로 넘어가면서 명칭이 많이 바뀌었는데요 !
v4와 v5에서의 변수명 변화
`v4 isLoading` = `v5 isPending`
`v4 isInitialLoading` = `v5 isLoading`

이렇게 바뀌었습니다.

2024-06-14 21:46 UTC, skiende74 commented on src/hooks/useFetchCart.ts
> +    isPending,
그리고 케빈이 리뷰를 주신 김에 
isLoading(구 isInitialLoading)과 isPending의 차이점과 의미차이를 명확히 정리해보았습니다.


### isPending vs isLoading(구 isInitialLoading)를 제대로 이해하고, 사용처의 기준을 세워본다면?

위 공식문서예시와, 아래 공식문서를 읽어본 결과
`보편적인경우에 isPending을 사용하고,  
lazy query를 이용해 로딩스피너를 만들때 isLoading을 사용하라는 것으로 해석되었습니다.`

> If you are using disabled or lazy queries, you can use the isLoading flag instead.
[isLoading - 공식문서](https://tanstack.com/query/latest/docs/framework/react/guides/disabling-queries#isloading-previously-isinitialloading)

그 이유는,
`isLoading === isPending && isFetching`인 파생플래그(derived flag)인데요.
isPending: 데이터가 준비되지않음.
isLoading: 데이터가 준비되지않았고, fetchFn이 백그라운드에서 동작중임.
인데,

사실 대부분의 경우에는 isPending과 isLoading은 같은 의미를 가지기 때문입니다.
(데이터가 준비되지 않았으면 당연히 가져오기위해 fetchFn이 동작 중.
동작이 끝났으면 당연히 데이터가 준비됨.)

하지만 둘의 차이는 lazy query에서 드러납니다. 
lazy query는 사용여부를 `on/off`할 수 있어, 
isPending이 true더라도, isFetching이 false일수가 있어서
데이터페칭을 하고있지도않은데 로딩스피너를 보여주는 불상사가 생기는 것을 방지하기위해
isLoading을 사용할 수 있습니다.
---

2024-06-15 19:44 UTC, JeongBin0227 approved these changes
안녕하세요 제이드!

코드 변경점이나 코멘트가 없어서 더이상 질문이 없는걸로 알고 머지하겠습니다~ 혹시나 추후에 궁금한점이 생기면 언제든지 물어봐 주세요!

2단계 미션 고생많으셨습니다~ 방학 잘보내세요! 💯

2024-06-15 19:45 UTC, merged